In [1]:
# Check whether easydiffraction is installed; install it if needed.
# Required for remote environments such as Google Colab.
import importlib.util

if importlib.util.find_spec('easydiffraction') is None:
    %pip install easydiffraction

# Structure Refinement: LBCO, HRPT

This minimalistic example is designed to show how Rietveld refinement
can be performed when both the crystal structure and experiment
parameters are defined using CIF files.

For this example, constant-wavelength neutron powder diffraction data
for La0.5Ba0.5CoO3 from HRPT at PSI is used.

It does not contain any advanced features or options, and includes no
comments or explanations—these can be found in the other tutorials.
Default values are used for all parameters if not specified. Only
essential and self-explanatory code is provided.

The example is intended for users who are already familiar with the
EasyDiffraction library and want to quickly get started with a simple
refinement. It is also useful for those who want to see what a
refinement might look like in code. For a more detailed explanation of
the code, please refer to the other tutorials.

## Import Library

In [2]:
import easydiffraction as ed

## Step 1: Define Project

In [3]:
# Create minimal project without name and description
project = ed.Project()

## Step 2: Define Crystal Structure

In [4]:
# Download CIF file from repository
structure_path = ed.download_data(id=1, destination='data')

Getting data...

Data #1: La0.5Ba0.5CoO3 (crystal structure)

✅ Data #1 downloaded to 'data/ed-1.cif'

In [5]:
# Add structure from downloaded CIF
project.structures.add_from_cif_path(structure_path)

## Step 3: Define Experiment

In [6]:
# Download CIF file from repository
expt_path = ed.download_data(id=2, destination='data')

Getting data...

Data #2: La0.5Ba0.5CoO3, HRPT (PSI), 300 K

✅ Data #2 downloaded to 'data/ed-2.cif'

In [7]:
# Add experiment from downloaded CIF
project.experiments.add_from_cif_path(expt_path)

## Step 4: Perform Analysis (cryspy)

In [8]:
# Define aliases and constraints for refinement. This is necessary to
# properly refine the isotropic displacement parameters of La and Ba,
# which are correlated due to their shared Wyckoff position.
project.analysis.aliases.create(
    label='biso_La',
    param=project.structures['lbco'].atom_sites['La'].b_iso,
)
project.analysis.aliases.create(
    label='biso_Ba',
    param=project.structures['lbco'].atom_sites['Ba'].b_iso,
)
project.analysis.constraints.create(expression='biso_Ba = biso_La')

In [9]:
# Start refinement. All parameters, which have standard uncertainties
# in the input CIF files, are refined by default.
project.analysis.fit()

Standard fitting

📋 Using experiment 🔬 'hrpt' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 1.29 at iteration 197

✅ Fitting complete.

In [10]:
# Show fit results summary
project.analysis.display.fit_results()

Fit results

✅ Success: True

⏱️ Fitting time: 11.49 seconds

📏 Goodness-of-fit (reduced χ²): 1.29

📏 R-factor (Rf): 5.62%

📏 R-factor squared (Rf²): 5.25%

📏 Weighted R-factor (wR): 4.40%

📈 Fitted parameters:

In [11]:
# Show defined experiment names
project.experiments.show_names()

Defined experiments 🔬

['hrpt']

In [12]:
# Plot measured vs. calculated diffraction patterns
project.plotter.plot_meas_vs_calc(expt_name='hrpt', show_residual=True)

## Step 5: Perform Analysis (crysfml)

In [13]:
# Change calculation engine from 'cryspy' to 'crysfml'
project.experiments['hrpt'].show_supported_calculator_types()
project.experiments['hrpt'].calculator_type = 'crysfml'

Supported calculator types

Calculator for experiment 'hrpt' changed to

crysfml

In [14]:
# Start refinement
project.analysis.fit()

Standard fitting

📋 Using experiment 🔬 'hrpt' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 2.04 at iteration 111

✅ Fitting complete.

In [15]:
# Show fit results summary
project.analysis.display.fit_results()

Fit results

✅ Success: True

⏱️ Fitting time: 5.91 seconds

📏 Goodness-of-fit (reduced χ²): 2.04

📏 R-factor (Rf): 6.27%

📏 R-factor squared (Rf²): 6.66%

📏 Weighted R-factor (wR): 5.22%

📈 Fitted parameters:

In [16]:
# Plot measured vs. calculated diffraction patterns
project.plotter.plot_meas_vs_calc(expt_name='hrpt', show_residual=True)