In [1]:
# Check if the easydiffraction library is installed.
# If not, install it with the 'visualization' extras.
# Needed when running remotely (e.g. Colab) where the lib is absent.
import builtins
import importlib.util

if (hasattr(builtins, '__IPYTHON__') and
    importlib.util.find_spec('easydiffraction') is None):
    !pip install 'easydiffraction[visualization]'

In [2]:
import easydiffraction as ed
from easydiffraction.datablocks.experiment.categories.background.factory import BackgroundFactory

In [3]:
project = ed.Project(name='lbco_hrpt')

In [4]:
project.experiments.create(
    name='hrpt',
    sample_form='powder',
    beam_mode='time-of-flight',  # 'constant wavelength'
    radiation_probe='neutron',
    scattering_type='bragg',
)

In [5]:
expt = project.experiments['hrpt']

In [6]:
expt.show_current_peak_profile_type()

Current peak profile type

PeakProfileTypeEnum.PSEUDO_VOIGT_IKEDA_CARPENTER

In [7]:
expt.show_supported_peak_profile_types()

Supported types

In [8]:
expt.show_current_background_type()

Current background type

BackgroundTypeEnum.LINE_SEGMENT

In [9]:
expt.show_supported_background_types()

Supported types

In [10]:
expt.background.show_supported()

❌ Unknown attribute 'show_supported' of <LineSegmentBackground>. Allowed readable/writable: 'as_cif', 'names', 'parameters',
   'unique_name'.

In [ ]:
expt.background_type = 'chebyshev'

In [ ]:
expt.show_current_background_type()

In [ ]:
expt.background_type = 'chebyshev'

In [ ]:
expt.show_current_background_type()

In [ ]:
print(expt.background)

In [ ]:
expt.background_type = 'line-segment'

In [ ]:
print(expt.background)

In [ ]:
expt.background.create(id='a', x=10.0, y=100.0)

In [ ]:
print(expt.background)

In [ ]:
expt.background['a']

In [ ]:
print(expt.background['a'])

In [ ]:
type(expt.background['a'])

In [ ]:
type(expt.background)

In [ ]:
expt.background.show()

In [ ]:
expt.show_as_cif()

In [ ]:
expt.background['a'].x = 2

In [ ]:
expt.background_type = 'chebyshev'

In [ ]:
expt.background['a'].x = 2

In [ ]:
bkg = BackgroundFactory.create('chebyshew')

In [ ]:
project.experiments['hrpt'].show_supported_calculator_types()

#### Show Defined Experiments

In [ ]:
project.experiments.show_names()

#### Show Measured Data

In [ ]:
project.plot_meas(expt_name='hrpt')

#### Set Instrument

Modify the default instrument parameters.

In [ ]:
project.experiments['hrpt'].instrument.setup_wavelength = 1.494
project.experiments['hrpt'].instrument.calib_twotheta_offset = 0.6

#### Set Peak Profile

Show supported peak profile types.

In [ ]:
project.experiments['hrpt'].show_supported_peak_profile_types()

Show the current peak profile type.

In [ ]:
project.experiments['hrpt'].show_current_peak_profile_type()

Select the desired peak profile type.

In [ ]:
project.experiments['hrpt'].peak_profile_type = 'pseudo-voigt'

Modify default peak profile parameters.

In [ ]:
project.experiments['hrpt'].peak.broad_gauss_u = 0.1
project.experiments['hrpt'].peak.broad_gauss_v = -0.1
project.experiments['hrpt'].peak.broad_gauss_w = 0.1
project.experiments['hrpt'].peak.broad_lorentz_x = 0
project.experiments['hrpt'].peak.broad_lorentz_y = 0.1

#### Set Background

Show supported background types.

In [ ]:
project.experiments['hrpt'].show_supported_background_types()

Show current background type.

In [ ]:
project.experiments['hrpt'].show_current_background_type()

Select the desired background type.

In [ ]:
project.experiments['hrpt'].background_type = 'line-segment'

Add background points.

In [ ]:
project.experiments['hrpt'].background.create(id='10', x=10, y=170)
project.experiments['hrpt'].background.create(id='30', x=30, y=170)
project.experiments['hrpt'].background.create(id='50', x=50, y=170)
project.experiments['hrpt'].background.create(id='110', x=110, y=170)
project.experiments['hrpt'].background.create(id='165', x=165, y=170)

Show current background points.

In [ ]:
project.experiments['hrpt'].background.show()

#### Set Linked Phases

Link the structure defined in the previous step to the experiment.

In [ ]:
project.experiments['hrpt'].linked_phases.create(id='lbco', scale=10.0)

#### Show Experiment as CIF

In [ ]:
project.experiments['hrpt'].show_as_cif()

#### Save Project State

In [ ]:
project.save()

## Step 4: Perform Analysis

This section explains the analysis process, including how to set up
calculation and fitting engines.

#### Set Calculator

Show supported calculation engines.

In [ ]:
project.experiments['hrpt'].show_supported_calculator_types()

Show current calculation engine.

In [ ]:
project.experiments['hrpt'].show_current_calculator_type()

Select the desired calculation engine.

In [ ]:
project.experiments['hrpt'].calculator_type = 'cryspy'

#### Show Calculated Data

In [ ]:
project.plot_calc(expt_name='hrpt')

#### Plot Measured vs Calculated

In [ ]:
project.plot_meas_vs_calc(expt_name='hrpt', show_residual=True)

In [ ]:
project.plot_meas_vs_calc(expt_name='hrpt', x_min=38, x_max=41, show_residual=True)

#### Show Parameters

Show all parameters of the project.

In [ ]:
# project.analysis.show_all_params()

Show all fittable parameters.

In [ ]:
project.analysis.show_fittable_params()

Show only free parameters.

In [ ]:
project.analysis.show_free_params()

Show how to access parameters in the code.

In [ ]:
# project.analysis.how_to_access_parameters()

#### Set Fit Mode

Show supported fit modes.

In [ ]:
project.analysis.show_available_fit_modes()

Show current fit mode.

In [ ]:
project.analysis.show_current_fit_mode()

Select desired fit mode.

In [ ]:
project.analysis.fit_mode = 'single'

#### Set Minimizer

Show supported fitting engines.

In [ ]:
project.analysis.show_available_minimizers()

Show current fitting engine.

In [ ]:
project.analysis.show_current_minimizer()

Select desired fitting engine.

In [ ]:
project.analysis.current_minimizer = 'lmfit (leastsq)'

### Perform Fit 1/5

Set structure parameters to be refined.

In [ ]:
project.structures['lbco'].cell.length_a.free = True

Set experiment parameters to be refined.

In [ ]:
project.experiments['hrpt'].linked_phases['lbco'].scale.free = True
project.experiments['hrpt'].instrument.calib_twotheta_offset.free = True
project.experiments['hrpt'].background['10'].y.free = True
project.experiments['hrpt'].background['30'].y.free = True
project.experiments['hrpt'].background['50'].y.free = True
project.experiments['hrpt'].background['110'].y.free = True
project.experiments['hrpt'].background['165'].y.free = True

Show free parameters after selection.

In [ ]:
project.analysis.show_free_params()

#### Run Fitting

In [ ]:
project.analysis.fit()
project.analysis.show_fit_results()

#### Plot Measured vs Calculated

In [ ]:
project.plot_meas_vs_calc(expt_name='hrpt', show_residual=True)

In [ ]:
project.plot_meas_vs_calc(expt_name='hrpt', x_min=38, x_max=41, show_residual=True)

#### Save Project State

In [ ]:
project.save_as(dir_path='lbco_hrpt', temporary=True)

### Perform Fit 2/5

Set more parameters to be refined.

In [ ]:
project.experiments['hrpt'].peak.broad_gauss_u.free = True
project.experiments['hrpt'].peak.broad_gauss_v.free = True
project.experiments['hrpt'].peak.broad_gauss_w.free = True
project.experiments['hrpt'].peak.broad_lorentz_y.free = True

Show free parameters after selection.

In [ ]:
project.analysis.show_free_params()

#### Run Fitting

In [ ]:
project.analysis.fit()
project.analysis.show_fit_results()

#### Plot Measured vs Calculated

In [ ]:
project.plot_meas_vs_calc(expt_name='hrpt', show_residual=True)

In [ ]:
project.plot_meas_vs_calc(expt_name='hrpt', x_min=38, x_max=41, show_residual=True)

#### Save Project State

In [ ]:
project.save_as(dir_path='lbco_hrpt', temporary=True)

### Perform Fit 3/5

Set more parameters to be refined.

In [ ]:
project.structures['lbco'].atom_sites['La'].b_iso.free = True
project.structures['lbco'].atom_sites['Ba'].b_iso.free = True
project.structures['lbco'].atom_sites['Co'].b_iso.free = True
project.structures['lbco'].atom_sites['O'].b_iso.free = True

Show free parameters after selection.

In [ ]:
project.analysis.show_free_params()

#### Run Fitting

In [ ]:
project.analysis.fit()
project.analysis.show_fit_results()

#### Plot Measured vs Calculated

In [ ]:
project.plot_meas_vs_calc(expt_name='hrpt', show_residual=True)

In [ ]:
project.plot_meas_vs_calc(expt_name='hrpt', x_min=38, x_max=41, show_residual=True)

#### Save Project State

In [ ]:
project.save_as(dir_path='lbco_hrpt', temporary=True)

### Perform Fit 4/5

#### Set Constraints

Set aliases for parameters.

In [ ]:
project.analysis.aliases.create(
    label='biso_La',
    param_uid=project.structures['lbco'].atom_sites['La'].b_iso.uid,
)
project.analysis.aliases.create(
    label='biso_Ba',
    param_uid=project.structures['lbco'].atom_sites['Ba'].b_iso.uid,
)

Set constraints.

In [ ]:
project.analysis.constraints.create(lhs_alias='biso_Ba', rhs_expr='biso_La')

Show defined constraints.

In [ ]:
project.analysis.show_constraints()

Show free parameters before applying constraints.

In [ ]:
project.analysis.show_free_params()

Apply constraints.

In [ ]:
project.analysis.apply_constraints()

Show free parameters after applying constraints.

In [ ]:
project.analysis.show_free_params()

#### Run Fitting

In [ ]:
project.analysis.fit()
project.analysis.show_fit_results()

#### Plot Measured vs Calculated

In [ ]:
project.plot_meas_vs_calc(expt_name='hrpt', show_residual=True)

In [ ]:
project.plot_meas_vs_calc(expt_name='hrpt', x_min=38, x_max=41, show_residual=True)

#### Save Project State

In [ ]:
project.save_as(dir_path='lbco_hrpt', temporary=True)

### Perform Fit 5/5

#### Set Constraints

Set more aliases for parameters.

In [ ]:
project.analysis.aliases.create(
    label='occ_La',
    param_uid=project.structures['lbco'].atom_sites['La'].occupancy.uid,
)
project.analysis.aliases.create(
    label='occ_Ba',
    param_uid=project.structures['lbco'].atom_sites['Ba'].occupancy.uid,
)

Set more constraints.

In [ ]:
project.analysis.constraints.create(
    lhs_alias='occ_Ba',
    rhs_expr='1 - occ_La',
)

Show defined constraints.

In [ ]:
project.analysis.show_constraints()

Apply constraints.

In [ ]:
project.analysis.apply_constraints()

Set structure parameters to be refined.

In [ ]:
project.structures['lbco'].atom_sites['La'].occupancy.free = True

Show free parameters after selection.

In [ ]:
project.analysis.show_free_params()

#### Run Fitting

In [ ]:
project.analysis.fit()
project.analysis.show_fit_results()

#### Plot Measured vs Calculated

In [ ]:
project.plot_meas_vs_calc(expt_name='hrpt', show_residual=True)

In [ ]:
project.plot_meas_vs_calc(expt_name='hrpt', x_min=38, x_max=41, show_residual=True)

#### Save Project State

In [ ]:
project.save_as(dir_path='lbco_hrpt', temporary=True)

## Step 5: Summary

This final section shows how to review the results of the analysis.

#### Show Project Summary

In [ ]:
project.summary.show_report()