In [1]:
# Check if the easydiffraction library is installed.
# If not, install it with the 'visualization' extras.
# Needed when running remotely (e.g. Colab) where the lib is absent.
import builtins
import importlib.util

if (hasattr(builtins, '__IPYTHON__') and
    importlib.util.find_spec('easydiffraction') is None):
    !pip install 'easydiffraction[visualization]'

# Structure Refinement: LBCO, HRPT

This minimalistic example is designed to show how Rietveld refinement
of a crystal structure can be performed when both the sample model and
experiment are defined directly in code. Only the experimentally
measured data is loaded from an external file.

For this example, constant-wavelength neutron powder diffraction data
for La0.5Ba0.5CoO3 from HRPT at PSI is used.

It does not contain any advanced features or options, and includes no
comments or explanations—these can be found in the other tutorials.
Default values are used for all parameters if not specified. Only
essential and self-explanatory code is provided.

The example is intended for users who are already familiar with the
EasyDiffraction library and want to quickly get started with a simple
refinement. It is also useful for those who want to see what a
refinement might look like in code. For a more detailed explanation of
the code, please refer to the other tutorials.

## Import Library

In [2]:
import easydiffraction as ed

## Step 1: Define Project

In [3]:
project = ed.Project()

## Step 2: Define Sample Model

In [4]:
project.sample_models.add(name='lbco')

In [5]:
sample_model = project.sample_models['lbco']

In [6]:
sample_model.space_group.name_h_m = 'P m -3 m'
sample_model.space_group.it_coordinate_system_code = '1'

In [7]:
sample_model.cell.length_a = 3.88

In [8]:
sample_model.atom_sites.add(
    label='La',
    type_symbol='La',
    fract_x=0,
    fract_y=0,
    fract_z=0,
    wyckoff_letter='a',
    b_iso=0.5,
    occupancy=0.5,
)
sample_model.atom_sites.add(
    label='Ba',
    type_symbol='Ba',
    fract_x=0,
    fract_y=0,
    fract_z=0,
    wyckoff_letter='a',
    b_iso=0.5,
    occupancy=0.5,
)
sample_model.atom_sites.add(
    label='Co',
    type_symbol='Co',
    fract_x=0.5,
    fract_y=0.5,
    fract_z=0.5,
    wyckoff_letter='b',
    b_iso=0.5,
)
sample_model.atom_sites.add(
    label='O',
    type_symbol='O',
    fract_x=0,
    fract_y=0.5,
    fract_z=0.5,
    wyckoff_letter='c',
    b_iso=0.5,
)

## Step 3: Define Experiment

In [9]:
data_path = ed.download_data(id=3, destination='data')

Getting data...

Data #3: La0.5Ba0.5CoO3, HRPT (PSI), 300 K

✅ Data #3 already present at 'data/ed-3.xye'. Keeping existing file.

In [10]:
project.experiments.add(
    name='hrpt',
    data_path=data_path,
    sample_form='powder',
    beam_mode='constant wavelength',
    radiation_probe='neutron',
)

Data loaded successfully

Experiment 🔬 'hrpt'. Number of data points: 3098

In [11]:
experiment = project.experiments['hrpt']

In [12]:
experiment.instrument.setup_wavelength = 1.494
experiment.instrument.calib_twotheta_offset = 0.6

In [13]:
experiment.peak.broad_gauss_u = 0.1
experiment.peak.broad_gauss_v = -0.1
experiment.peak.broad_gauss_w = 0.1
experiment.peak.broad_lorentz_y = 0.1

In [14]:
experiment.background.add(id='1', x=10, y=170)
experiment.background.add(id='2', x=30, y=170)
experiment.background.add(id='3', x=50, y=170)
experiment.background.add(id='4', x=110, y=170)
experiment.background.add(id='5', x=165, y=170)

In [15]:
experiment.excluded_regions.add(id='1', start=0, end=5)
experiment.excluded_regions.add(id='2', start=165, end=180)

In [16]:
experiment.linked_phases.add(id='lbco', scale=10.0)

## Step 4: Perform Analysis

In [17]:
sample_model.cell.length_a.free = True

sample_model.atom_sites['La'].b_iso.free = True
sample_model.atom_sites['Ba'].b_iso.free = True
sample_model.atom_sites['Co'].b_iso.free = True
sample_model.atom_sites['O'].b_iso.free = True

In [18]:
experiment.instrument.calib_twotheta_offset.free = True

experiment.peak.broad_gauss_u.free = True
experiment.peak.broad_gauss_v.free = True
experiment.peak.broad_gauss_w.free = True
experiment.peak.broad_lorentz_y.free = True

experiment.background['1'].y.free = True
experiment.background['2'].y.free = True
experiment.background['3'].y.free = True
experiment.background['4'].y.free = True
experiment.background['5'].y.free = True

experiment.linked_phases['lbco'].scale.free = True

In [19]:
project.analysis.fit()
project.analysis.show_fit_results()

Using experiment 🔬 'hrpt' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 1.29 at iteration 275

✅ Fitting complete.

Fit results

✅ Success: True

⏱️ Fitting time: 18.02 seconds

📏 Goodness-of-fit (reduced χ²): 1.29

📏 R-factor (Rf): 5.63%

📏 R-factor squared (Rf²): 5.27%

📏 Weighted R-factor (wR): 4.41%

📈 Fitted parameters:

In [20]:
project.plot_meas_vs_calc(expt_name='hrpt', show_residual=True)