In [1]:
# Check whether easydiffraction is installed; install it if needed.
# Required for remote environments such as Google Colab.
import importlib.util

if importlib.util.find_spec('easydiffraction') is None:
    %pip install easydiffraction

# Pair Distribution Function: Ni, NPD

This example demonstrates a pair distribution function (PDF) analysis
of Ni, based on data collected from a constant wavelength neutron
powder diffraction experiment.

The dataset is taken from:
https://github.com/diffpy/cmi_exchange/tree/main/cmi_scripts/fitNiPDF

## Import Library

In [2]:
import easydiffraction as ed

## Create Project

In [3]:
project = ed.Project()

## Add Structure

In [4]:
project.structures.create(name='ni')

In [5]:
project.structures['ni'].space_group.name_h_m = 'F m -3 m'
project.structures['ni'].space_group.it_coordinate_system_code = '1'
project.structures['ni'].cell.length_a = 3.52387
project.structures['ni'].atom_sites.create(
    label='Ni',
    type_symbol='Ni',
    fract_x=0.0,
    fract_y=0.0,
    fract_z=0.0,
    wyckoff_letter='a',
    adp_iso=0.5,
)

## Add Experiment

In [6]:
data_path = ed.download_data(id=6, destination='data')

Getting data...

Data #6: ni-q27r100-neutron_from-2.gr

✅ Data #6 downloaded to 'data/ed-6.gr'

In [7]:
project.experiments.add_from_data_path(
    name='pdf',
    data_path=data_path,
    sample_form='powder',
    beam_mode='constant wavelength',
    radiation_probe='neutron',
    scattering_type='total',
)

⚠️ No uncertainty (sy) column provided. Defaulting to 0.03.

Data loaded successfully

Experiment 🔬 'pdf'. Number of data points: 9801.

In [8]:
project.experiments['pdf'].linked_phases.create(id='ni', scale=1.0)
project.experiments['pdf'].peak.damp_q = 0
project.experiments['pdf'].peak.broad_q = 0.03
project.experiments['pdf'].peak.cutoff_q = 27.0
project.experiments['pdf'].peak.sharp_delta_1 = 0.0
project.experiments['pdf'].peak.sharp_delta_2 = 2.0
project.experiments['pdf'].peak.damp_particle_diameter = 0

## Select Fitting Parameters

In [9]:
project.structures['ni'].cell.length_a.free = True
project.structures['ni'].atom_sites['Ni'].adp_iso.free = True

In [10]:
project.experiments['pdf'].linked_phases['ni'].scale.free = True
project.experiments['pdf'].peak.broad_q.free = True
project.experiments['pdf'].peak.sharp_delta_2.free = True

## Run Fitting

In [11]:
project.analysis.fit()
project.analysis.display.fit_results()
project.plotter.plot_param_correlations()

Standard fitting

📋 Using experiment 🔬 'pdf' for 'single' fitting

🚀 Starting fit process with 'bumps (lm)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 207.10 at iteration 45

✅ Fitting complete.

Fit results

✅ Success: True

⏱️ Fitting time: 80.48 seconds

📏 Goodness-of-fit (reduced χ²): 207.10

📏 R-factor (Rf): 9.83%

📏 R-factor squared (Rf²): 9.48%

📏 Weighted R-factor (wR): 9.48%

📈 Fitted parameters:

⚠️ Correlation matrix is unavailable for this fit. Use the lmfit minimizer and ensure covariance estimation succeeds.

## Plot Measured vs Calculated

In [12]:
project.plotter.plot_meas_vs_calc(expt_name='pdf', show_residual=True)