In [1]:
# Check whether easydiffraction is installed; install it if needed.
# Required for remote environments such as Google Colab.
import importlib.util

if importlib.util.find_spec('easydiffraction') is None:
    %pip install easydiffraction==0.11.1

# Structure Refinement: Si, SEPD

This example demonstrates a Rietveld refinement of Si crystal
structure using time-of-flight neutron powder diffraction data from
SEPD at Argonne.

## Import Library

In [2]:
from easydiffraction import ExperimentFactory
from easydiffraction import Project
from easydiffraction import StructureFactory
from easydiffraction import download_data

## Define Structure

This section shows how to add structures and modify their
parameters.

#### Create Structure

In [3]:
structure = StructureFactory.from_scratch(name='si')

#### Set Space Group

In [4]:
structure.space_group.name_h_m = 'F d -3 m'
structure.space_group.it_coordinate_system_code = '2'

#### Set Unit Cell

In [5]:
structure.cell.length_a = 5.431

#### Set Atom Sites

In [6]:
structure.atom_sites.create(
    label='Si',
    type_symbol='Si',
    fract_x=0.125,
    fract_y=0.125,
    fract_z=0.125,
    b_iso=0.5,
)

## Define Experiment

This section shows how to add experiments, configure their
parameters, and link the structures defined in the previous step.

#### Download Measured Data

In [7]:
data_path = download_data(id=7, destination='data')

Getting data...

Data #7: Si, SEPD (Argonne)

✅ Data #7 already present at 'data/ed-7.xye'. Keeping existing file.

#### Create Experiment

In [8]:
expt = ExperimentFactory.from_data_path(
    name='sepd', data_path=data_path, beam_mode='time-of-flight'
)

Data loaded successfully

Experiment 🔬 'sepd'. Number of data points: 5600.

#### Set Instrument

In [9]:
expt.instrument.setup_twotheta_bank = 144.845
expt.instrument.calib_d_to_tof_offset = 0.0
expt.instrument.calib_d_to_tof_linear = 7476.91
expt.instrument.calib_d_to_tof_quad = -1.54

#### Set Peak Profile

In [10]:
expt.peak_profile_type = 'pseudo-voigt * ikeda-carpenter'
expt.peak.broad_gauss_sigma_0 = 3.0
expt.peak.broad_gauss_sigma_1 = 40.0
expt.peak.broad_gauss_sigma_2 = 2.0
expt.peak.broad_mix_beta_0 = 0.04221
expt.peak.broad_mix_beta_1 = 0.00946

⚠️ Switching peak profile type discards existing peak parameters.

Peak profile type for experiment 'sepd' changed to

pseudo-voigt * ikeda-carpenter

#### Set Peak Asymmetry

In [11]:
expt.peak.asym_alpha_0 = 0.0
expt.peak.asym_alpha_1 = 0.5971

#### Set Background

In [12]:
expt.background_type = 'line-segment'
for x in range(0, 35000, 5000):
    expt.background.create(id=str(x), x=x, y=200)

Background type for experiment 'sepd' already set to

line-segment

#### Set Linked Phases

In [13]:
expt.linked_phases.create(id='si', scale=10.0)

## Define Project

The project object is used to manage the structure, experiment, and
analysis.

#### Create Project

In [14]:
project = Project()

#### Add Structure

In [15]:
project.structures.add(structure)

#### Add Experiment

In [16]:
project.experiments.add(expt)

## Perform Analysis

This section shows the analysis process, including how to set up
calculation and fitting engines.

#### Set Minimizer

In [17]:
project.analysis.current_minimizer = 'lmfit'

Current minimizer changed to

lmfit

#### Plot Measured vs Calculated

In [18]:
project.plot_meas_vs_calc(expt_name='sepd', show_residual=True)
project.plot_meas_vs_calc(expt_name='sepd', x_min=23200, x_max=23700, show_residual=True)

### Perform Fit 1/5

Set parameters to be refined.

In [19]:
structure.cell.length_a.free = True

expt.linked_phases['si'].scale.free = True
expt.instrument.calib_d_to_tof_offset.free = True

Show free parameters after selection.

In [20]:
project.analysis.show_free_params()

Free parameters for both structures (🧩 data blocks) and experiments (🔬 data blocks)

#### Run Fitting

In [21]:
project.analysis.fit()
project.analysis.show_fit_results()

Using experiment 🔬 'sepd' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 66.72 at iteration 26

✅ Fitting complete.

Fit results

✅ Success: True

⏱️ Fitting time: 10.34 seconds

📏 Goodness-of-fit (reduced χ²): 66.72

📏 R-factor (Rf): 23.08%

📏 R-factor squared (Rf²): 12.55%

📏 Weighted R-factor (wR): 12.51%

📈 Fitted parameters:

#### Plot Measured vs Calculated

In [22]:
project.plot_meas_vs_calc(expt_name='sepd', show_residual=True)

In [23]:
project.plot_meas_vs_calc(expt_name='sepd', x_min=23200, x_max=23700, show_residual=True)

### Perform Fit 2/5

Set more parameters to be refined.

In [24]:
for point in expt.background:
    point.y.free = True

Show free parameters after selection.

In [25]:
project.analysis.show_free_params()

Free parameters for both structures (🧩 data blocks) and experiments (🔬 data blocks)

#### Run Fitting

In [26]:
project.analysis.fit()
project.analysis.show_fit_results()

Using experiment 🔬 'sepd' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 3.38 at iteration 47

✅ Fitting complete.

Fit results

✅ Success: True

⏱️ Fitting time: 16.00 seconds

📏 Goodness-of-fit (reduced χ²): 3.38

📏 R-factor (Rf): 9.29%

📏 R-factor squared (Rf²): 6.33%

📏 Weighted R-factor (wR): 5.95%

📈 Fitted parameters:

#### Plot Measured vs Calculated

In [27]:
project.plot_meas_vs_calc(expt_name='sepd', show_residual=True)

In [28]:
project.plot_meas_vs_calc(expt_name='sepd', x_min=23200, x_max=23700, show_residual=True)

### Perform Fit 3/5

Fix background points.

In [29]:
for point in expt.background:
    point.y.free = False

Set more parameters to be refined.

In [30]:
expt.peak.broad_gauss_sigma_0.free = True
expt.peak.broad_gauss_sigma_1.free = True
expt.peak.broad_gauss_sigma_2.free = True

Show free parameters after selection.

In [31]:
project.analysis.show_free_params()

Free parameters for both structures (🧩 data blocks) and experiments (🔬 data blocks)

#### Run Fitting

In [32]:
project.analysis.fit()
project.analysis.show_fit_results()

Using experiment 🔬 'sepd' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 3.21 at iteration 38

✅ Fitting complete.

Fit results

✅ Success: True

⏱️ Fitting time: 12.94 seconds

📏 Goodness-of-fit (reduced χ²): 3.21

📏 R-factor (Rf): 8.99%

📏 R-factor squared (Rf²): 5.52%

📏 Weighted R-factor (wR): 4.88%

📈 Fitted parameters:

#### Plot Measured vs Calculated

In [33]:
project.plot_meas_vs_calc(expt_name='sepd', show_residual=True)

In [34]:
project.plot_meas_vs_calc(expt_name='sepd', x_min=23200, x_max=23700, show_residual=True)

### Perform Fit 4/5

Set more parameters to be refined.

In [35]:
structure.atom_sites['Si'].b_iso.free = True

Show free parameters after selection.

In [36]:
project.analysis.show_free_params()

Free parameters for both structures (🧩 data blocks) and experiments (🔬 data blocks)

#### Run Fitting

In [37]:
project.analysis.fit()
project.analysis.show_fit_results()

Using experiment 🔬 'sepd' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 3.19 at iteration 43

✅ Fitting complete.

Fit results

✅ Success: True

⏱️ Fitting time: 14.54 seconds

📏 Goodness-of-fit (reduced χ²): 3.19

📏 R-factor (Rf): 9.01%

📏 R-factor squared (Rf²): 5.35%

📏 Weighted R-factor (wR): 4.47%

📈 Fitted parameters:

#### Plot Measured vs Calculated

In [38]:
project.plot_meas_vs_calc(expt_name='sepd', show_residual=True)

In [39]:
project.plot_meas_vs_calc(expt_name='sepd', x_min=23200, x_max=23700, show_residual=True)