In [1]:
# Check whether easydiffraction is installed; install it if needed.
# Required for remote environments such as Google Colab.
import importlib.util

if importlib.util.find_spec('easydiffraction') is None:
    %pip install easydiffraction

# Structure Refinement: Si, SEPD

This example demonstrates a Rietveld refinement of Si crystal
structure using time-of-flight neutron powder diffraction data from
SEPD at Argonne.

It also shows how to switch calculation engine and peak profile type.

## Import Library

In [2]:
from easydiffraction import ExperimentFactory
from easydiffraction import Project
from easydiffraction import StructureFactory
from easydiffraction import download_data

## Define Structure

This section shows how to add structures and modify their
parameters.

#### Create Structure

In [3]:
structure = StructureFactory.from_scratch(name='si')

#### Set Space Group

In [4]:
structure.space_group.name_h_m = 'F d -3 m'
structure.space_group.it_coordinate_system_code = '2'

#### Set Unit Cell

In [5]:
structure.cell.length_a = 5.431

#### Set Atom Sites

In [6]:
structure.atom_sites.create(
    label='Si',
    type_symbol='Si',
    fract_x=0.125,
    fract_y=0.125,
    fract_z=0.125,
    adp_iso=0.5,
)

## Define Experiment

This section shows how to add experiments, configure their
parameters, and link the structures defined in the previous step.

#### Download Measured Data

In [7]:
data_path = download_data(id=7, destination='data')

Getting data...

Data #7: Si, SEPD (Argonne)

✅ Data #7 already present at 'data/ed-7.xye'. Keeping existing file.

#### Create Experiment

In [8]:
expt = ExperimentFactory.from_data_path(
    name='sepd', data_path=data_path, beam_mode='time-of-flight'
)

#### Set Instrument

In [9]:
expt.instrument.setup_twotheta_bank = 144.845
expt.instrument.calib_d_to_tof_offset = 0.0
expt.instrument.calib_d_to_tof_linear = 7476.91
expt.instrument.calib_d_to_tof_quad = -1.54

#### Set Peak Profile

In [10]:
expt.show_peak_profile_types()
expt.peak.broad_gauss_sigma_0 = 3.0
expt.peak.broad_gauss_sigma_1 = 40.0
expt.peak.broad_gauss_sigma_2 = 2.0
expt.peak.exp_decay_beta_0 = 0.04221
expt.peak.exp_decay_beta_1 = 0.00946
expt.peak.exp_rise_alpha_0 = 0.0
expt.peak.exp_rise_alpha_1 = 0.5971

Peak profile types

#### Set Background

In [11]:
expt.background_type = 'line-segment'
for x in range(0, 35000, 5000):
    expt.background.create(id=str(x), x=x, y=200)

Background type for experiment 'sepd' already set to

line-segment

#### Set Linked Phases

In [12]:
expt.linked_phases.create(id='si', scale=10.0)

## Define Project

The project object is used to manage the structure, experiment, and
analysis.

#### Create Project

In [13]:
project = Project()

#### Add Structure

In [14]:
project.structures.add(structure)

#### Add Experiment

In [15]:
project.experiments.add(expt)

## Perform Analysis

This section shows the analysis process, including how to set up
calculation and fitting engines.

#### Plot Measured vs Calculated

In [16]:
project.display.plotter.plot_meas_vs_calc(expt_name='sepd', show_residual=True)
project.display.plotter.plot_meas_vs_calc(
    expt_name='sepd', x_min=23200, x_max=23700, show_residual=True
)

### Perform Fit 1/5

Set parameters to be refined.

In [17]:
structure.cell.length_a.free = True

expt.linked_phases['si'].scale.free = True
expt.instrument.calib_d_to_tof_offset.free = True

Show free parameters after selection.

In [18]:
project.analysis.display.free_params()

Free parameters for both structures (🧩 data blocks) and experiments (🔬 data blocks)

#### Run Fitting

In [19]:
project.analysis.fit()
project.analysis.display.fit_results()

Standard fitting

📋 Using experiment 🔬 'sepd' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 66.72 at iteration 26

✅ Fitting complete.

Fit results

✅ Success: True

⏱️ Fitting time: 11.00 seconds

📏 Goodness-of-fit (reduced χ²): 66.72

📏 R-factor (Rf): 23.08%

📏 R-factor squared (Rf²): 12.55%

📏 Weighted R-factor (wR): 12.51%

📈 Fitted parameters:

#### Plot Measured vs Calculated

In [20]:
project.display.plotter.plot_meas_vs_calc(expt_name='sepd', show_residual=True)

In [21]:
project.display.plotter.plot_meas_vs_calc(
    expt_name='sepd', x_min=23200, x_max=23700, show_residual=True
)

### Perform Fit 2/5

Set more parameters to be refined.

In [22]:
for point in expt.background:
    point.y.free = True

Show free parameters after selection.

In [23]:
project.analysis.display.free_params()

Free parameters for both structures (🧩 data blocks) and experiments (🔬 data blocks)

#### Run Fitting

In [24]:
project.analysis.fit()
project.analysis.display.fit_results()

Standard fitting

📋 Using experiment 🔬 'sepd' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 3.38 at iteration 47

✅ Fitting complete.

Fit results

✅ Success: True

⏱️ Fitting time: 16.92 seconds

📏 Goodness-of-fit (reduced χ²): 3.38

📏 R-factor (Rf): 9.29%

📏 R-factor squared (Rf²): 6.33%

📏 Weighted R-factor (wR): 5.95%

📈 Fitted parameters:

#### Plot Measured vs Calculated

In [25]:
project.display.plotter.plot_meas_vs_calc(expt_name='sepd', show_residual=True)

In [26]:
project.display.plotter.plot_meas_vs_calc(
    expt_name='sepd', x_min=23200, x_max=23700, show_residual=True
)

### Perform Fit 3/5

Fix background points.

In [27]:
for point in expt.background:
    point.y.free = False

Set more parameters to be refined.

In [28]:
expt.peak.broad_gauss_sigma_0.free = True
expt.peak.broad_gauss_sigma_1.free = True
expt.peak.broad_gauss_sigma_2.free = True

Show free parameters after selection.

In [29]:
project.analysis.display.free_params()

Free parameters for both structures (🧩 data blocks) and experiments (🔬 data blocks)

#### Run Fitting

In [30]:
project.analysis.fit()
project.analysis.display.fit_results()

Standard fitting

📋 Using experiment 🔬 'sepd' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 3.21 at iteration 38

✅ Fitting complete.

Fit results

✅ Success: True

⏱️ Fitting time: 13.60 seconds

📏 Goodness-of-fit (reduced χ²): 3.21

📏 R-factor (Rf): 8.99%

📏 R-factor squared (Rf²): 5.52%

📏 Weighted R-factor (wR): 4.88%

📈 Fitted parameters:

#### Plot Measured vs Calculated

In [31]:
project.display.plotter.plot_meas_vs_calc(expt_name='sepd', show_residual=True)

In [32]:
project.display.plotter.plot_meas_vs_calc(
    expt_name='sepd', x_min=23200, x_max=23700, show_residual=True
)

### Perform Fit 4/5

Set more parameters to be refined.

In [33]:
structure.atom_sites['Si'].adp_iso.free = True

expt.peak.exp_decay_beta_0.free = True
expt.peak.exp_decay_beta_1.free = True
expt.peak.exp_rise_alpha_1.free = True

Show free parameters after selection.

In [34]:
project.analysis.display.free_params()

Free parameters for both structures (🧩 data blocks) and experiments (🔬 data blocks)

#### Run Fitting

In [35]:
project.analysis.fit()
project.analysis.display.fit_results()

Standard fitting

📋 Using experiment 🔬 'sepd' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 2.93 at iteration 104

✅ Fitting complete.

Fit results

✅ Success: True

⏱️ Fitting time: 36.53 seconds

📏 Goodness-of-fit (reduced χ²): 2.93

📏 R-factor (Rf): 8.39%

📏 R-factor squared (Rf²): 4.16%

📏 Weighted R-factor (wR): 2.48%

📈 Fitted parameters:

#### Show parameter correlations

In [36]:
project.display.plotter.plot_param_correlations()

⚠️ No parameter pairs with |correlation| >= 0.70 were found.

#### Plot Measured vs Calculated

In [37]:
project.display.plotter.plot_meas_vs_calc(expt_name='sepd', show_residual=True)

In [38]:
project.display.plotter.plot_meas_vs_calc(
    expt_name='sepd', x_min=23200, x_max=23700, show_residual=True
)

In [39]:
project.display.plotter.plot_meas_vs_calc(expt_name='sepd', x='d_spacing', show_residual=True)

### Perform Fit 5/5

#### Switch calculator engine

In [40]:
expt.calculation.show_calculator_types()

Calculator types

In [41]:
expt.calculation.calculator_type = 'crysfml'

Calculator for experiment 'sepd' changed to

crysfml

#### Change peak profile type

In [42]:
expt.show_peak_profile_types()

Peak profile types

In [43]:
expt.peak_profile_type = 'jorgensen-von-dreele'

⚠️ Switching peak profile type discards existing peak parameters.

Peak profile type for experiment 'sepd' changed to

jorgensen-von-dreele

In [44]:
expt.peak.broad_gauss_sigma_0 = 3.0148
expt.peak.broad_gauss_sigma_1 = 33.3451
expt.peak.broad_lorentz_gamma_1 = 2.5489
expt.peak.exp_decay_beta_0 = 0.04221
expt.peak.exp_decay_beta_1 = 0.00946
expt.peak.exp_rise_alpha_1 = 0.5971

#### Add new free parameters

In [45]:
expt.peak.broad_gauss_sigma_0.free = True
expt.peak.broad_gauss_sigma_1.free = True
expt.peak.broad_lorentz_gamma_1.free = True
expt.peak.exp_decay_beta_0.free = True
expt.peak.exp_decay_beta_1.free = True
expt.peak.exp_rise_alpha_1.free = True

#### Run Fitting

In [46]:
project.analysis.fit()
project.analysis.display.fit_results()

Standard fitting

📋 Using experiment 🔬 'sepd' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 2.85 at iteration 317

✅ Fitting complete.

Fit results

✅ Success: True

⏱️ Fitting time: 114.57 seconds

📏 Goodness-of-fit (reduced χ²): 2.85

📏 R-factor (Rf): 7.99%

📏 R-factor squared (Rf²): 3.87%

📏 Weighted R-factor (wR): 2.41%

📈 Fitted parameters:

#### Show parameter correlations

In [47]:
project.display.plotter.plot_param_correlations()

⚠️ Correlation matrix is unavailable for this fit. Use the lmfit minimizer and ensure covariance estimation succeeds.

#### Plot Measured vs Calculated

In [48]:
project.display.plotter.plot_meas_vs_calc(
    expt_name='sepd', x_min=23200, x_max=23700, show_residual=True
)

In [49]:
project.display.plotter.plot_meas_vs_calc(expt_name='sepd', x='d_spacing', show_residual=True)