In [1]:
# Check whether easydiffraction is installed; install it if needed.
# Required for remote environments such as Google Colab.
import importlib.util

if importlib.util.find_spec('easydiffraction') is None:
    %pip install easydiffraction==0.15.0

# Structure Refinement: LBCO, HRPT

This example demonstrates how to use the EasyDiffraction API in a
simplified, user-friendly manner that closely follows the GUI workflow
for a Rietveld refinement of La0.5Ba0.5CoO3 crystal structure using
constant wavelength neutron powder diffraction data from HRPT at PSI.

It is intended for users with minimal programming experience who want
to learn how to perform standard crystal structure fitting using
diffraction data. This script covers creating a project, adding
crystal structures and experiments, performing analysis, and refining
parameters.

Only a single import of `easydiffraction` is required, and all
operations are performed through high-level components of the
`project` object, such as `project.structures`,
`project.experiments`, and `project.analysis`. The `project` object is
the main container for all information.

## Import Library

In [2]:
import easydiffraction as ed

## Step 1: Create a Project

This section explains how to create a project and define its metadata.

#### Create Project

In [3]:
project = ed.Project(name='lbco_hrpt')

#### Set Project Metadata

In [4]:
project.info.title = 'La0.5Ba0.5CoO3 at HRPT@PSI'
project.info.description = """This project demonstrates a standard
refinement of La0.5Ba0.5CoO3, which crystallizes in a perovskite-type
structure, using neutron powder diffraction data collected in constant
wavelength mode at the HRPT diffractometer (PSI)."""

#### Show Project Metadata as CIF

In [5]:
project.info.show_as_cif()

Project 📦 'lbco_hrpt' info as CIF

#### Save Project

When saving the project for the first time, you need to specify the
directory path. In the example below, the project is saved to a
temporary location defined by the system.

In [6]:
project.save_as(dir_path='lbco_hrpt', temporary=True)

Saving project 📦 'lbco_hrpt' to

/tmp/lbco_hrpt

├── 📄 project.cif

├── 📁 structures/

├── 📁 experiments/

├── 📁 analysis/

│   └── 📄 analysis.cif

└── 📄 summary.cif

#### Set Up Data Plotter

Show supported plotting engines.

In [7]:
project.display.plotter.show_supported_engines()

Supported engines

Show current plotting configuration.

In [8]:
project.display.plotter.show_config()

Current plotter configuration

## Step 2: Define Structure

This section shows how to add structures and modify their
parameters.

#### Add Structure

In [9]:
project.structures.create(name='lbco')

#### Show Defined Structures

Show the names of the crystal structures added. These names are used
to access the structure using the syntax:
`project.structures[name]`. All structure parameters can be accessed
via the `project` object.

In [10]:
project.structures.show_names()

Defined structures 🧩

['lbco']

#### Set Space Group

Modify the default space group parameters.

In [11]:
project.structures['lbco'].space_group.name_h_m = 'P m -3 m'
project.structures['lbco'].space_group.it_coordinate_system_code = '1'

#### Set Unit Cell

Modify the default unit cell parameters.

In [12]:
project.structures['lbco'].cell.length_a = 3.88

#### Set Atom Sites

Add atom sites to the structure.

In [13]:
project.structures['lbco'].atom_sites.create(
    label='La',
    type_symbol='La',
    fract_x=0,
    fract_y=0,
    fract_z=0,
    wyckoff_letter='a',
    adp_iso=0.5,
    occupancy=0.5,
)
project.structures['lbco'].atom_sites.create(
    label='Ba',
    type_symbol='Ba',
    fract_x=0,
    fract_y=0,
    fract_z=0,
    wyckoff_letter='a',
    adp_iso=0.5,
    occupancy=0.5,
)
project.structures['lbco'].atom_sites.create(
    label='Co',
    type_symbol='Co',
    fract_x=0.5,
    fract_y=0.5,
    fract_z=0.5,
    wyckoff_letter='b',
    adp_iso=0.5,
)
project.structures['lbco'].atom_sites.create(
    label='O',
    type_symbol='O',
    fract_x=0,
    fract_y=0.5,
    fract_z=0.5,
    wyckoff_letter='c',
    adp_iso=0.5,
)

#### Show Structure as CIF

In [14]:
project.structures['lbco'].show_as_cif()

Structure 🧩 'lbco' as cif

#### Show Structure Structure

In [15]:
project.structures['lbco'].show()

Structure 🧩 'lbco'

Not implemented yet.

#### Save Project State

Save the project state after adding the structure. This ensures
that all changes are stored and can be accessed later. The project
state is saved in the directory specified during project creation.

In [16]:
project.save()

Saving project 📦 'lbco_hrpt' to

/tmp/lbco_hrpt

├── 📄 project.cif

├── 📁 structures/

│   └── 📄 lbco.cif

├── 📁 experiments/

├── 📁 analysis/

│   └── 📄 analysis.cif

└── 📄 summary.cif

## Step 3: Define Experiment

This section shows how to add experiments, configure their parameters,
and link the structures defined in the previous step.

#### Download Measured Data

Download the data file from the EasyDiffraction repository on GitHub.

In [17]:
data_path = ed.download_data(id=3, destination='data')

Getting data...

Data #3: La0.5Ba0.5CoO3, HRPT (PSI), 300 K

✅ Data #3 already present at 'data/ed-3.xye'. Keeping existing file.

#### Add Diffraction Experiment

In [18]:
project.experiments.add_from_data_path(
    name='hrpt',
    data_path=data_path,
    sample_form='powder',
    beam_mode='constant wavelength',
    radiation_probe='neutron',
)

Data loaded successfully

Experiment 🔬 'hrpt'. Number of data points: 3098.

#### Show Defined Experiments

In [19]:
project.experiments.show_names()

Defined experiments 🔬

['hrpt']

#### Show Measured Data

In [20]:
project.display.plotter.plot_meas(expt_name='hrpt')

Warning: No linked phases defined. Returning empty pattern.

#### Set Instrument

Modify the default instrument parameters.

In [21]:
project.experiments['hrpt'].instrument.setup_wavelength = 1.494
project.experiments['hrpt'].instrument.calib_twotheta_offset = 0.6

#### Set Peak Profile

Show supported peak profile types.

In [22]:
project.experiments['hrpt'].show_peak_profile_types()

Peak profile types

Select the desired peak profile type.

In [23]:
project.experiments['hrpt'].peak_profile_type = 'pseudo-voigt'

⚠️ Switching peak profile type discards existing peak parameters.

Peak profile type for experiment 'hrpt' changed to

pseudo-voigt

Modify default peak profile parameters.

In [24]:
project.experiments['hrpt'].peak.broad_gauss_u = 0.1
project.experiments['hrpt'].peak.broad_gauss_v = -0.1
project.experiments['hrpt'].peak.broad_gauss_w = 0.1
project.experiments['hrpt'].peak.broad_lorentz_x = 0
project.experiments['hrpt'].peak.broad_lorentz_y = 0.1

#### Set Background

Show supported background types.

In [25]:
project.experiments['hrpt'].show_background_types()

Background types

Select the desired background type.

In [26]:
project.experiments['hrpt'].background_type = 'line-segment'

Background type for experiment 'hrpt' already set to

line-segment

Add background points.

In [27]:
project.experiments['hrpt'].background.create(id='10', x=10, y=170)
project.experiments['hrpt'].background.create(id='30', x=30, y=170)
project.experiments['hrpt'].background.create(id='50', x=50, y=170)
project.experiments['hrpt'].background.create(id='110', x=110, y=170)
project.experiments['hrpt'].background.create(id='165', x=165, y=170)

Show current background points.

In [28]:
project.experiments['hrpt'].background.show()

Line-segment background points

#### Set Linked Phases

Link the structure defined in the previous step to the experiment.

In [29]:
project.experiments['hrpt'].linked_phases.create(id='lbco', scale=10.0)

#### Show Experiment as CIF

In [30]:
project.experiments['hrpt'].show_as_cif()

Experiment 🔬 'hrpt' as cif

#### Save Project State

In [31]:
project.save()

Saving project 📦 'lbco_hrpt' to

/tmp/lbco_hrpt

├── 📄 project.cif

├── 📁 structures/

│   └── 📄 lbco.cif

├── 📁 experiments/

│   └── 📄 hrpt.cif

├── 📁 analysis/

│   └── 📄 analysis.cif

└── 📄 summary.cif

## Step 4: Perform Analysis

This section explains the analysis process, including how to set up
calculation and fitting engines.

#### Set Calculator

Show supported calculation engines for this experiment.

In [32]:
project.experiments['hrpt'].calculation.show_calculator_types()

Calculator types

Select the desired calculation engine.

In [33]:
project.experiments['hrpt'].calculation.calculator_type = 'cryspy'

Calculator for experiment 'hrpt' already set to

cryspy

#### Show Calculated Data

In [34]:
project.display.plotter.plot_calc(expt_name='hrpt')

#### Plot Measured vs Calculated

In [35]:
project.display.plotter.plot_meas_vs_calc(expt_name='hrpt', show_residual=True)

In [36]:
project.display.plotter.plot_meas_vs_calc(expt_name='hrpt', x_min=38, x_max=41, show_residual=True)

#### Show Parameters

Show all parameters of the project.

In [37]:
# project.analysis.display.all_params()

Show all fittable parameters.

In [38]:
project.analysis.display.fittable_params()

Fittable parameters for all structures (🧩 data blocks)

Fittable parameters for all experiments (🔬 data blocks)

Show only free parameters.

In [39]:
project.analysis.display.free_params()

⚠️ No free parameters found.

Show how to access parameters in the code.

In [40]:
# project.analysis.display.how_to_access_parameters()

#### Set Fit Mode

Show supported fit modes.

In [41]:
project.analysis.fit.show_modes()

Fit modes

Select desired fit mode.

In [42]:
project.analysis.fit.mode = 'single'

#### Set Minimizer

Show supported fitting engines.

In [43]:
project.analysis.fit.show_minimizer_types()

Minimizer types

Select desired fitting engine.

In [44]:
project.analysis.fit.minimizer_type = 'lmfit'

Current minimizer changed to

lmfit

### Perform Fit 1/5

Set structure parameters to be refined.

In [45]:
project.structures['lbco'].cell.length_a.free = True

Set experiment parameters to be refined.

In [46]:
project.experiments['hrpt'].linked_phases['lbco'].scale.free = True
project.experiments['hrpt'].instrument.calib_twotheta_offset.free = True
project.experiments['hrpt'].background['10'].y.free = True
project.experiments['hrpt'].background['30'].y.free = True
project.experiments['hrpt'].background['50'].y.free = True
project.experiments['hrpt'].background['110'].y.free = True
project.experiments['hrpt'].background['165'].y.free = True

Show free parameters after selection.

In [47]:
project.analysis.display.free_params()

Free parameters for both structures (🧩 data blocks) and experiments (🔬 data blocks)

#### Run Fitting

In [48]:
project.analysis.fit()
project.analysis.display.fit_results()

Standard fitting

📋 Using experiment 🔬 'hrpt' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 3.14 at iteration 69

✅ Fitting complete.

Saving project 📦 'lbco_hrpt' to

/tmp/lbco_hrpt

├── 📄 project.cif

├── 📁 structures/

│   └── 📄 lbco.cif

├── 📁 experiments/

│   └── 📄 hrpt.cif

├── 📁 analysis/

│   └── 📄 analysis.cif

└── 📄 summary.cif

Fit results

✅ Success: True

⏱️ Fitting time: 4.32 seconds

📏 Goodness-of-fit (reduced χ²): 3.14

📏 R-factor (Rf): 8.42%

📏 R-factor squared (Rf²): 11.79%

📏 Weighted R-factor (wR): 11.62%

📈 Fitted parameters:

#### Plot Measured vs Calculated

In [49]:
project.display.plotter.plot_meas_vs_calc(expt_name='hrpt', show_residual=True)

In [50]:
project.display.plotter.plot_meas_vs_calc(expt_name='hrpt', x_min=38, x_max=41, show_residual=True)

#### Save Project State

In [51]:
project.save_as(dir_path='lbco_hrpt', temporary=True)

Saving project 📦 'lbco_hrpt' to

/tmp/lbco_hrpt

├── 📄 project.cif

├── 📁 structures/

│   └── 📄 lbco.cif

├── 📁 experiments/

│   └── 📄 hrpt.cif

├── 📁 analysis/

│   └── 📄 analysis.cif

└── 📄 summary.cif

### Perform Fit 2/5

Set more parameters to be refined.

In [52]:
project.experiments['hrpt'].peak.broad_gauss_u.free = True
project.experiments['hrpt'].peak.broad_gauss_v.free = True
project.experiments['hrpt'].peak.broad_gauss_w.free = True
project.experiments['hrpt'].peak.broad_lorentz_y.free = True

Show free parameters after selection.

In [53]:
project.analysis.display.free_params()

Free parameters for both structures (🧩 data blocks) and experiments (🔬 data blocks)

#### Run Fitting

In [54]:
project.analysis.fit()
project.analysis.display.fit_results()

Standard fitting

📋 Using experiment 🔬 'hrpt' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 2.85 at iteration 68

✅ Fitting complete.

Saving project 📦 'lbco_hrpt' to

/tmp/lbco_hrpt

├── 📄 project.cif

├── 📁 structures/

│   └── 📄 lbco.cif

├── 📁 experiments/

│   └── 📄 hrpt.cif

├── 📁 analysis/

│   └── 📄 analysis.cif

└── 📄 summary.cif

Fit results

✅ Success: True

⏱️ Fitting time: 3.55 seconds

📏 Goodness-of-fit (reduced χ²): 2.85

📏 R-factor (Rf): 8.30%

📏 R-factor squared (Rf²): 11.85%

📏 Weighted R-factor (wR): 11.91%

📈 Fitted parameters:

#### Plot Measured vs Calculated

In [55]:
project.display.plotter.plot_meas_vs_calc(expt_name='hrpt', show_residual=True)

In [56]:
project.display.plotter.plot_meas_vs_calc(expt_name='hrpt', x_min=38, x_max=41, show_residual=True)

#### Save Project State

In [57]:
project.save_as(dir_path='lbco_hrpt', temporary=True)

Saving project 📦 'lbco_hrpt' to

/tmp/lbco_hrpt

├── 📄 project.cif

├── 📁 structures/

│   └── 📄 lbco.cif

├── 📁 experiments/

│   └── 📄 hrpt.cif

├── 📁 analysis/

│   └── 📄 analysis.cif

└── 📄 summary.cif

### Perform Fit 3/5

Set more parameters to be refined.

In [58]:
project.structures['lbco'].atom_sites['La'].adp_iso.free = True
project.structures['lbco'].atom_sites['Ba'].adp_iso.free = True
project.structures['lbco'].atom_sites['Co'].adp_iso.free = True
project.structures['lbco'].atom_sites['O'].adp_iso.free = True

Show free parameters after selection.

In [59]:
project.analysis.display.free_params()

Free parameters for both structures (🧩 data blocks) and experiments (🔬 data blocks)

#### Run Fitting

In [60]:
project.analysis.fit()
project.analysis.display.fit_results()

Standard fitting

📋 Using experiment 🔬 'hrpt' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 1.29 at iteration 187

✅ Fitting complete.

Saving project 📦 'lbco_hrpt' to

/tmp/lbco_hrpt

├── 📄 project.cif

├── 📁 structures/

│   └── 📄 lbco.cif

├── 📁 experiments/

│   └── 📄 hrpt.cif

├── 📁 analysis/

│   └── 📄 analysis.cif

└── 📄 summary.cif

Fit results

✅ Success: True

⏱️ Fitting time: 10.64 seconds

📏 Goodness-of-fit (reduced χ²): 1.29

📏 R-factor (Rf): 5.63%

📏 R-factor squared (Rf²): 5.27%

📏 Weighted R-factor (wR): 4.41%

📈 Fitted parameters:

⚠️ Red uncertainty: exceeds the fitted value (consider adding constraints)

#### Plot Measured vs Calculated

In [61]:
project.display.plotter.plot_meas_vs_calc(expt_name='hrpt', show_residual=True)

In [62]:
project.display.plotter.plot_meas_vs_calc(expt_name='hrpt', x_min=38, x_max=41, show_residual=True)

#### Save Project State

In [63]:
project.save_as(dir_path='lbco_hrpt', temporary=True)

Saving project 📦 'lbco_hrpt' to

/tmp/lbco_hrpt

├── 📄 project.cif

├── 📁 structures/

│   └── 📄 lbco.cif

├── 📁 experiments/

│   └── 📄 hrpt.cif

├── 📁 analysis/

│   └── 📄 analysis.cif

└── 📄 summary.cif

### Perform Fit 4/5

#### Set Constraints

Set aliases for parameters.

In [64]:
project.analysis.aliases.create(
    label='biso_La',
    param=project.structures['lbco'].atom_sites['La'].adp_iso,
)
project.analysis.aliases.create(
    label='biso_Ba',
    param=project.structures['lbco'].atom_sites['Ba'].adp_iso,
)

Set constraints.

In [65]:
project.analysis.constraints.create(expression='biso_Ba = biso_La')

Show defined constraints.

In [66]:
project.analysis.display.constraints()

User defined constraints

Constraints enabled: True

Show free parameters.

In [67]:
project.analysis.display.free_params()

Free parameters for both structures (🧩 data blocks) and experiments (🔬 data blocks)

#### Run Fitting

In [68]:
project.analysis.fit()
project.analysis.display.fit_results()

Standard fitting

📋 Using experiment 🔬 'hrpt' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 1.29 at iteration 19

✅ Fitting complete.

Saving project 📦 'lbco_hrpt' to

/tmp/lbco_hrpt

├── 📄 project.cif

├── 📁 structures/

│   └── 📄 lbco.cif

├── 📁 experiments/

│   └── 📄 hrpt.cif

├── 📁 analysis/

│   └── 📄 analysis.cif

└── 📄 summary.cif

Fit results

✅ Success: True

⏱️ Fitting time: 1.13 seconds

📏 Goodness-of-fit (reduced χ²): 1.29

📏 R-factor (Rf): 5.63%

📏 R-factor squared (Rf²): 5.27%

📏 Weighted R-factor (wR): 4.41%

📈 Fitted parameters:

#### Plot Measured vs Calculated

In [69]:
project.display.plotter.plot_meas_vs_calc(expt_name='hrpt', show_residual=True)

In [70]:
project.display.plotter.plot_meas_vs_calc(expt_name='hrpt', x_min=38, x_max=41, show_residual=True)

#### Save Project State

In [71]:
project.save_as(dir_path='lbco_hrpt', temporary=True)

Saving project 📦 'lbco_hrpt' to

/tmp/lbco_hrpt

├── 📄 project.cif

├── 📁 structures/

│   └── 📄 lbco.cif

├── 📁 experiments/

│   └── 📄 hrpt.cif

├── 📁 analysis/

│   └── 📄 analysis.cif

└── 📄 summary.cif

### Perform Fit 5/5

#### Set Constraints

Set more aliases for parameters.

In [72]:
project.analysis.aliases.create(
    label='occ_La',
    param=project.structures['lbco'].atom_sites['La'].occupancy,
)
project.analysis.aliases.create(
    label='occ_Ba',
    param=project.structures['lbco'].atom_sites['Ba'].occupancy,
)

Set more constraints.

In [73]:
project.analysis.constraints.create(
    expression='occ_Ba = 1 - occ_La',
)

Show defined constraints.

In [74]:
project.analysis.display.constraints()

User defined constraints

Constraints enabled: True

Set structure parameters to be refined.

In [75]:
project.structures['lbco'].atom_sites['La'].occupancy.free = True

Show free parameters after selection.

In [76]:
project.analysis.display.free_params()

Free parameters for both structures (🧩 data blocks) and experiments (🔬 data blocks)

#### Run Fitting

In [77]:
project.analysis.fit()
project.analysis.display.fit_results()
project.display.plotter.plot_param_correlations()

Standard fitting

📋 Using experiment 🔬 'hrpt' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 1.28 at iteration 54

✅ Fitting complete.

Saving project 📦 'lbco_hrpt' to

/tmp/lbco_hrpt

├── 📄 project.cif

├── 📁 structures/

│   └── 📄 lbco.cif

├── 📁 experiments/

│   └── 📄 hrpt.cif

├── 📁 analysis/

│   └── 📄 analysis.cif

└── 📄 summary.cif

Fit results

✅ Success: True

⏱️ Fitting time: 2.74 seconds

📏 Goodness-of-fit (reduced χ²): 1.28

📏 R-factor (Rf): 5.61%

📏 R-factor squared (Rf²): 5.25%

📏 Weighted R-factor (wR): 4.39%

📈 Fitted parameters:

#### Plot Measured vs Calculated

In [78]:
project.display.plotter.plot_meas_vs_calc(expt_name='hrpt', show_residual=True)

In [79]:
project.display.plotter.plot_meas_vs_calc(expt_name='hrpt', x_min=38, x_max=41, show_residual=True)

#### Save Project State

In [80]:
project.save_as(dir_path='lbco_hrpt', temporary=True)

Saving project 📦 'lbco_hrpt' to

/tmp/lbco_hrpt

├── 📄 project.cif

├── 📁 structures/

│   └── 📄 lbco.cif

├── 📁 experiments/

│   └── 📄 hrpt.cif

├── 📁 analysis/

│   └── 📄 analysis.cif

└── 📄 summary.cif

## Step 5: Summary

This final section shows how to review the results of the analysis.

#### Show Project Summary

In [81]:
project.summary.show_report()

————————————
PROJECT INFO
————————————

Title

La0.5Ba0.5CoO3 at HRPT@PSI

Description

This project demonstrates a standard refinement of
La0.5Ba0.5CoO3, which crystallizes in a perovskite-type
structure, using neutron powder diffraction data collected
in constant wavelength mode at the HRPT diffractometer
(PSI).
—————————————————————
CRYSTALLOGRAPHIC DATA
—————————————————————

Phase datablock

🧩 lbco

Space group

P m -3 m

Atom sites

———————————
EXPERIMENTS
———————————

Experiment datablock

🔬 hrpt

Experiment type

powder, neutron, constant wavelength bragg

Calculation engine

cryspy

Wavelength

1.49400

2θ offset

0.62261

Profile type

pseudo-voigt

Peak broadening (Gaussian)

Peak broadening (Lorentzian)

———————
FITTING
———————

Minimization engine

lmfit

Fit quality