In [1]:
# Check if the easydiffraction library is installed.
# If not, install it with the 'visualization' extras.
# Needed when running remotely (e.g. Colab) where the lib is absent.
import builtins
import importlib.util

if (hasattr(builtins, '__IPYTHON__') and
    importlib.util.find_spec('easydiffraction') is None):
    !pip install 'easydiffraction[visualization]'

# Structure Refinement: LBCO, HRPT

This example demonstrates how to use the EasyDiffraction API in a
simplified, user-friendly manner that closely follows the GUI workflow
for a Rietveld refinement of La0.5Ba0.5CoO3 crystal structure using
constant wavelength neutron powder diffraction data from HRPT at PSI.

It is intended for users with minimal programming experience who want
to learn how to perform standard crystal structure fitting using
diffraction data. This script covers creating a project, adding sample
models and experiments, performing analysis, and refining parameters.

Only a single import of `easydiffraction` is required, and all
operations are performed through high-level components of the
`project` object, such as `project.sample_models`,
`project.experiments`, and `project.analysis`. The `project` object is
the main container for all information.

## Import Library

In [2]:
import easydiffraction as ed

## Step 1: Create a Project

This section explains how to create a project and define its metadata.

#### Create Project

In [3]:
project = ed.Project(name='lbco_hrpt')

#### Set Project Metadata

In [4]:
project.info.title = 'La0.5Ba0.5CoO3 at HRPT@PSI'
project.info.description = """This project demonstrates a standard
refinement of La0.5Ba0.5CoO3, which crystallizes in a perovskite-type
structure, using neutron powder diffraction data collected in constant
wavelength mode at the HRPT diffractometer (PSI)."""

#### Show Project Metadata as CIF

In [5]:
project.info.show_as_cif()

Project 📦 'lbco_hrpt' info as CIF

#### Save Project

When saving the project for the first time, you need to specify the
directory path. In the example below, the project is saved to a
temporary location defined by the system.

In [6]:
project.save_as(dir_path='lbco_hrpt', temporary=True)

Saving project 📦 'lbco_hrpt' to

/private/var/folders/nb/lcynqsvj2fvf0gqkbj2_nxwh0000gn/T/lbco_hrpt

├── 📄 project.cif

├── 📄 analysis.cif

└── 📄 summary.cif

#### Set Up Data Plotter

Show supported plotting engines.

In [7]:
project.plotter.show_supported_engines()

Supported engines

Show current plotting configuration.

In [8]:
project.plotter.show_config()

Current plotter configuration

Set plotting engine.

In [9]:
# Keep the auto-selected engine. Alternatively, you can uncomment the
# line below to explicitly set the engine to the required one.
# project.plotter.engine = 'plotly'

## Step 2: Define Sample Model

This section shows how to add sample models and modify their
parameters.

#### Add Sample Model

In [10]:
project.sample_models.add(name='lbco')

#### Show Defined Sample Models

Show the names of the models added. These names are used to access the
model using the syntax: `project.sample_models['model_name']`. All
model parameters can be accessed via the `project` object.

In [11]:
project.sample_models.show_names()

Defined sample models 🧩

['lbco']

#### Set Space Group

Modify the default space group parameters.

In [12]:
project.sample_models['lbco'].space_group.name_h_m = 'P m -3 m'
project.sample_models['lbco'].space_group.it_coordinate_system_code = '1'

#### Set Unit Cell

Modify the default unit cell parameters.

In [13]:
project.sample_models['lbco'].cell.length_a = 3.88

#### Set Atom Sites

Add atom sites to the sample model.

In [14]:
project.sample_models['lbco'].atom_sites.add(
    label='La',
    type_symbol='La',
    fract_x=0,
    fract_y=0,
    fract_z=0,
    wyckoff_letter='a',
    b_iso=0.5,
    occupancy=0.5,
)
project.sample_models['lbco'].atom_sites.add(
    label='Ba',
    type_symbol='Ba',
    fract_x=0,
    fract_y=0,
    fract_z=0,
    wyckoff_letter='a',
    b_iso=0.5,
    occupancy=0.5,
)
project.sample_models['lbco'].atom_sites.add(
    label='Co',
    type_symbol='Co',
    fract_x=0.5,
    fract_y=0.5,
    fract_z=0.5,
    wyckoff_letter='b',
    b_iso=0.5,
)
project.sample_models['lbco'].atom_sites.add(
    label='O',
    type_symbol='O',
    fract_x=0,
    fract_y=0.5,
    fract_z=0.5,
    wyckoff_letter='c',
    b_iso=0.5,
)

#### Show Sample Model as CIF

In [15]:
project.sample_models['lbco'].show_as_cif()

Sample model 🧩 'lbco' as cif

#### Show Sample Model Structure

In [16]:
project.sample_models['lbco'].show_structure()

Sample model 🧩 'lbco' structure view

Not implemented yet.

#### Save Project State

Save the project state after adding the sample model. This ensures
that all changes are stored and can be accessed later. The project
state is saved in the directory specified during project creation.

In [17]:
project.save()

Saving project 📦 'lbco_hrpt' to

/private/var/folders/nb/lcynqsvj2fvf0gqkbj2_nxwh0000gn/T/lbco_hrpt

├── 📄 project.cif

├── 📁 sample_models

│   └── 📄 lbco.cif

├── 📄 analysis.cif

└── 📄 summary.cif

## Step 3: Define Experiment

This section shows how to add experiments, configure their parameters,
and link the sample models defined in the previous step.

#### Download Measured Data

Download the data file from the EasyDiffraction repository on GitHub.

In [18]:
data_path = ed.download_data(id=3, destination='data')

Getting data...

Data #3: La0.5Ba0.5CoO3, HRPT (PSI), 300 K

✅ Data #3 already present at 'data/ed-3.xye'. Keeping existing file.

#### Add Diffraction Experiment

In [19]:
project.experiments.add(
    name='hrpt',
    data_path=data_path,
    sample_form='powder',
    beam_mode='constant wavelength',
    radiation_probe='neutron',
)

Data loaded successfully

Experiment 🔬 'hrpt'. Number of data points: 3098

#### Show Defined Experiments

In [20]:
project.experiments.show_names()

Defined experiments 🔬

['hrpt']

#### Show Measured Data

In [21]:
project.plot_meas(expt_name='hrpt')

Warning: No linked phases defined. Returning empty pattern.

#### Set Instrument

Modify the default instrument parameters.

In [22]:
project.experiments['hrpt'].instrument.setup_wavelength = 1.494
project.experiments['hrpt'].instrument.calib_twotheta_offset = 0.6

#### Set Peak Profile

Show supported peak profile types.

In [23]:
project.experiments['hrpt'].show_supported_peak_profile_types()

Supported peak profile types

Show the current peak profile type.

In [24]:
project.experiments['hrpt'].show_current_peak_profile_type()

Current peak profile type

PeakProfileTypeEnum.PSEUDO_VOIGT

Select the desired peak profile type.

In [25]:
project.experiments['hrpt'].peak_profile_type = 'pseudo-voigt'

Peak profile type for experiment 'hrpt' changed to

pseudo-voigt

Modify default peak profile parameters.

In [26]:
project.experiments['hrpt'].peak.broad_gauss_u = 0.1
project.experiments['hrpt'].peak.broad_gauss_v = -0.1
project.experiments['hrpt'].peak.broad_gauss_w = 0.1
project.experiments['hrpt'].peak.broad_lorentz_x = 0
project.experiments['hrpt'].peak.broad_lorentz_y = 0.1

#### Set Background

Show supported background types.

In [27]:
project.experiments['hrpt'].show_supported_background_types()

Supported background types

Show current background type.

In [28]:
project.experiments['hrpt'].show_current_background_type()

Current background type

BackgroundTypeEnum.LINE_SEGMENT

Select the desired background type.

In [29]:
project.experiments['hrpt'].background_type = 'line-segment'

Background type for experiment 'hrpt' changed to

line-segment

Add background points.

In [30]:
project.experiments['hrpt'].background.add(id='10', x=10, y=170)
project.experiments['hrpt'].background.add(id='30', x=30, y=170)
project.experiments['hrpt'].background.add(id='50', x=50, y=170)
project.experiments['hrpt'].background.add(id='110', x=110, y=170)
project.experiments['hrpt'].background.add(id='165', x=165, y=170)

Show current background points.

In [31]:
project.experiments['hrpt'].background.show()

Line-segment background points

#### Set Linked Phases

Link the sample model defined in the previous step to the experiment.

In [32]:
project.experiments['hrpt'].linked_phases.add(id='lbco', scale=10.0)

#### Show Experiment as CIF

In [33]:
project.experiments['hrpt'].show_as_cif()

Experiment 🔬 'hrpt' as cif

#### Save Project State

In [34]:
project.save()

Saving project 📦 'lbco_hrpt' to

/private/var/folders/nb/lcynqsvj2fvf0gqkbj2_nxwh0000gn/T/lbco_hrpt

├── 📄 project.cif

├── 📁 sample_models

│   └── 📄 lbco.cif

├── 📁 experiments

│   └── 📄 hrpt.cif

├── 📄 analysis.cif

└── 📄 summary.cif

## Step 4: Perform Analysis

This section explains the analysis process, including how to set up
calculation and fitting engines.

#### Set Calculator

Show supported calculation engines.

In [35]:
project.analysis.show_supported_calculators()

Supported calculators

Show current calculation engine.

In [36]:
project.analysis.show_current_calculator()

Current calculator

cryspy

Select the desired calculation engine.

In [37]:
project.analysis.current_calculator = 'cryspy'

Current calculator changed to

cryspy

#### Show Calculated Data

In [38]:
project.plot_calc(expt_name='hrpt')

#### Plot Measured vs Calculated

In [39]:
project.plot_meas_vs_calc(expt_name='hrpt', show_residual=True)

In [40]:
project.plot_meas_vs_calc(expt_name='hrpt', x_min=38, x_max=41, show_residual=True)

#### Show Parameters

Show all parameters of the project.

In [41]:
# project.analysis.show_all_params()

Show all fittable parameters.

In [42]:
project.analysis.show_fittable_params()

Fittable parameters for all sample models (🧩 data blocks)

Fittable parameters for all experiments (🔬 data blocks)

Show only free parameters.

In [43]:
project.analysis.show_free_params()

⚠️ No free parameters found.

Show how to access parameters in the code.

In [44]:
# project.analysis.how_to_access_parameters()

#### Set Fit Mode

Show supported fit modes.

In [45]:
project.analysis.show_available_fit_modes()

Available fit modes

Show current fit mode.

In [46]:
project.analysis.show_current_fit_mode()

Current fit mode

single

Select desired fit mode.

In [47]:
project.analysis.fit_mode = 'single'

Current fit mode changed to

single

#### Set Minimizer

Show supported fitting engines.

In [48]:
project.analysis.show_available_minimizers()

Supported minimizers

Show current fitting engine.

In [49]:
project.analysis.show_current_minimizer()

Current minimizer

lmfit (leastsq)

Select desired fitting engine.

In [50]:
project.analysis.current_minimizer = 'lmfit (leastsq)'

Current minimizer changed to

lmfit (leastsq)

### Perform Fit 1/5

Set sample model parameters to be refined.

In [51]:
project.sample_models['lbco'].cell.length_a.free = True

Set experiment parameters to be refined.

In [52]:
project.experiments['hrpt'].linked_phases['lbco'].scale.free = True
project.experiments['hrpt'].instrument.calib_twotheta_offset.free = True
project.experiments['hrpt'].background['10'].y.free = True
project.experiments['hrpt'].background['30'].y.free = True
project.experiments['hrpt'].background['50'].y.free = True
project.experiments['hrpt'].background['110'].y.free = True
project.experiments['hrpt'].background['165'].y.free = True

Show free parameters after selection.

In [53]:
project.analysis.show_free_params()

Free parameters for both sample models (🧩 data blocks) and experiments (🔬 data blocks)

#### Run Fitting

In [54]:
project.analysis.fit()
project.analysis.show_fit_results()

Using experiment 🔬 'hrpt' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 3.14 at iteration 69

✅ Fitting complete.

Fit results

✅ Success: True

⏱️ Fitting time: 4.29 seconds

📏 Goodness-of-fit (reduced χ²): 3.14

📏 R-factor (Rf): 8.42%

📏 R-factor squared (Rf²): 11.79%

📏 Weighted R-factor (wR): 11.62%

📈 Fitted parameters:

#### Plot Measured vs Calculated

In [55]:
project.plot_meas_vs_calc(expt_name='hrpt', show_residual=True)

In [56]:
project.plot_meas_vs_calc(expt_name='hrpt', x_min=38, x_max=41, show_residual=True)

#### Save Project State

In [57]:
project.save_as(dir_path='lbco_hrpt', temporary=True)

Saving project 📦 'lbco_hrpt' to

/private/var/folders/nb/lcynqsvj2fvf0gqkbj2_nxwh0000gn/T/lbco_hrpt

├── 📄 project.cif

├── 📁 sample_models

│   └── 📄 lbco.cif

├── 📁 experiments

│   └── 📄 hrpt.cif

├── 📄 analysis.cif

└── 📄 summary.cif

### Perform Fit 2/5

Set more parameters to be refined.

In [58]:
project.experiments['hrpt'].peak.broad_gauss_u.free = True
project.experiments['hrpt'].peak.broad_gauss_v.free = True
project.experiments['hrpt'].peak.broad_gauss_w.free = True
project.experiments['hrpt'].peak.broad_lorentz_y.free = True

Show free parameters after selection.

In [59]:
project.analysis.show_free_params()

Free parameters for both sample models (🧩 data blocks) and experiments (🔬 data blocks)

#### Run Fitting

In [60]:
project.analysis.fit()
project.analysis.show_fit_results()

Using experiment 🔬 'hrpt' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 2.85 at iteration 68

✅ Fitting complete.

Fit results

✅ Success: True

⏱️ Fitting time: 2.83 seconds

📏 Goodness-of-fit (reduced χ²): 2.85

📏 R-factor (Rf): 8.30%

📏 R-factor squared (Rf²): 11.85%

📏 Weighted R-factor (wR): 11.91%

📈 Fitted parameters:

#### Plot Measured vs Calculated

In [61]:
project.plot_meas_vs_calc(expt_name='hrpt', show_residual=True)

In [62]:
project.plot_meas_vs_calc(expt_name='hrpt', x_min=38, x_max=41, show_residual=True)

#### Save Project State

In [63]:
project.save_as(dir_path='lbco_hrpt', temporary=True)

Saving project 📦 'lbco_hrpt' to

/private/var/folders/nb/lcynqsvj2fvf0gqkbj2_nxwh0000gn/T/lbco_hrpt

├── 📄 project.cif

├── 📁 sample_models

│   └── 📄 lbco.cif

├── 📁 experiments

│   └── 📄 hrpt.cif

├── 📄 analysis.cif

└── 📄 summary.cif

### Perform Fit 3/5

Set more parameters to be refined.

In [64]:
project.sample_models['lbco'].atom_sites['La'].b_iso.free = True
project.sample_models['lbco'].atom_sites['Ba'].b_iso.free = True
project.sample_models['lbco'].atom_sites['Co'].b_iso.free = True
project.sample_models['lbco'].atom_sites['O'].b_iso.free = True

Show free parameters after selection.

In [65]:
project.analysis.show_free_params()

Free parameters for both sample models (🧩 data blocks) and experiments (🔬 data blocks)

#### Run Fitting

In [66]:
project.analysis.fit()
project.analysis.show_fit_results()

Using experiment 🔬 'hrpt' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 1.29 at iteration 187

✅ Fitting complete.

Fit results

✅ Success: True

⏱️ Fitting time: 8.46 seconds

📏 Goodness-of-fit (reduced χ²): 1.29

📏 R-factor (Rf): 5.63%

📏 R-factor squared (Rf²): 5.27%

📏 Weighted R-factor (wR): 4.41%

📈 Fitted parameters:

#### Plot Measured vs Calculated

In [67]:
project.plot_meas_vs_calc(expt_name='hrpt', show_residual=True)

In [68]:
project.plot_meas_vs_calc(expt_name='hrpt', x_min=38, x_max=41, show_residual=True)

#### Save Project State

In [69]:
project.save_as(dir_path='lbco_hrpt', temporary=True)

Saving project 📦 'lbco_hrpt' to

/private/var/folders/nb/lcynqsvj2fvf0gqkbj2_nxwh0000gn/T/lbco_hrpt

├── 📄 project.cif

├── 📁 sample_models

│   └── 📄 lbco.cif

├── 📁 experiments

│   └── 📄 hrpt.cif

├── 📄 analysis.cif

└── 📄 summary.cif

### Perform Fit 4/5

#### Set Constraints

Set aliases for parameters.

In [70]:
project.analysis.aliases.add(
    label='biso_La',
    param_uid=project.sample_models['lbco'].atom_sites['La'].b_iso.uid,
)
project.analysis.aliases.add(
    label='biso_Ba',
    param_uid=project.sample_models['lbco'].atom_sites['Ba'].b_iso.uid,
)

Set constraints.

In [71]:
project.analysis.constraints.add(lhs_alias='biso_Ba', rhs_expr='biso_La')

Show defined constraints.

In [72]:
project.analysis.show_constraints()

User defined constraints

Show free parameters before applying constraints.

In [73]:
project.analysis.show_free_params()

Free parameters for both sample models (🧩 data blocks) and experiments (🔬 data blocks)

Apply constraints.

In [74]:
project.analysis.apply_constraints()

Show free parameters after applying constraints.

In [75]:
project.analysis.show_free_params()

Free parameters for both sample models (🧩 data blocks) and experiments (🔬 data blocks)

#### Run Fitting

In [76]:
project.analysis.fit()
project.analysis.show_fit_results()

Using experiment 🔬 'hrpt' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 1.29 at iteration 19

✅ Fitting complete.

Fit results

✅ Success: True

⏱️ Fitting time: 0.84 seconds

📏 Goodness-of-fit (reduced χ²): 1.29

📏 R-factor (Rf): 5.63%

📏 R-factor squared (Rf²): 5.27%

📏 Weighted R-factor (wR): 4.41%

📈 Fitted parameters:

#### Plot Measured vs Calculated

In [77]:
project.plot_meas_vs_calc(expt_name='hrpt', show_residual=True)

In [78]:
project.plot_meas_vs_calc(expt_name='hrpt', x_min=38, x_max=41, show_residual=True)

#### Save Project State

In [79]:
project.save_as(dir_path='lbco_hrpt', temporary=True)

Saving project 📦 'lbco_hrpt' to

/private/var/folders/nb/lcynqsvj2fvf0gqkbj2_nxwh0000gn/T/lbco_hrpt

├── 📄 project.cif

├── 📁 sample_models

│   └── 📄 lbco.cif

├── 📁 experiments

│   └── 📄 hrpt.cif

├── 📄 analysis.cif

└── 📄 summary.cif

### Perform Fit 5/5

#### Set Constraints

Set more aliases for parameters.

In [80]:
project.analysis.aliases.add(
    label='occ_La',
    param_uid=project.sample_models['lbco'].atom_sites['La'].occupancy.uid,
)
project.analysis.aliases.add(
    label='occ_Ba',
    param_uid=project.sample_models['lbco'].atom_sites['Ba'].occupancy.uid,
)

Set more constraints.

In [81]:
project.analysis.constraints.add(
    lhs_alias='occ_Ba',
    rhs_expr='1 - occ_La',
)

Show defined constraints.

In [82]:
project.analysis.show_constraints()

User defined constraints

Apply constraints.

In [83]:
project.analysis.apply_constraints()

Set sample model parameters to be refined.

In [84]:
project.sample_models['lbco'].atom_sites['La'].occupancy.free = True

Show free parameters after selection.

In [85]:
project.analysis.show_free_params()

Free parameters for both sample models (🧩 data blocks) and experiments (🔬 data blocks)

#### Run Fitting

In [86]:
project.analysis.fit()
project.analysis.show_fit_results()

Using experiment 🔬 'hrpt' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 1.28 at iteration 54

✅ Fitting complete.

Fit results

✅ Success: True

⏱️ Fitting time: 2.33 seconds

📏 Goodness-of-fit (reduced χ²): 1.28

📏 R-factor (Rf): 5.61%

📏 R-factor squared (Rf²): 5.25%

📏 Weighted R-factor (wR): 4.39%

📈 Fitted parameters:

#### Plot Measured vs Calculated

In [87]:
project.plot_meas_vs_calc(expt_name='hrpt', show_residual=True)

In [88]:
project.plot_meas_vs_calc(expt_name='hrpt', x_min=38, x_max=41, show_residual=True)

#### Save Project State

In [89]:
project.save_as(dir_path='lbco_hrpt', temporary=True)

Saving project 📦 'lbco_hrpt' to

/private/var/folders/nb/lcynqsvj2fvf0gqkbj2_nxwh0000gn/T/lbco_hrpt

├── 📄 project.cif

├── 📁 sample_models

│   └── 📄 lbco.cif

├── 📁 experiments

│   └── 📄 hrpt.cif

├── 📄 analysis.cif

└── 📄 summary.cif

## Step 5: Summary

This final section shows how to review the results of the analysis.

#### Show Project Summary

In [90]:
project.summary.show_report()

————————————
PROJECT INFO
————————————

Title

La0.5Ba0.5CoO3 at HRPT@PSI

Description

This project demonstrates a standard refinement of
La0.5Ba0.5CoO3, which crystallizes in a perovskite-type
structure, using neutron powder diffraction data collected
in constant wavelength mode at the HRPT diffractometer
(PSI).
—————————————————————
CRYSTALLOGRAPHIC DATA
—————————————————————

Phase datablock

🧩 lbco

Space group

P m -3 m

Cell parameters

Atom sites

———————————
EXPERIMENTS
———————————

Experiment datablock

🔬 hrpt

Experiment type

powder, neutron, constant wavelength

Wavelength

1.49400

2θ offset

0.62261

Profile type

PeakProfileTypeEnum.PSEUDO_VOIGT

Peak broadening (Gaussian)

Peak broadening (Lorentzian)

———————
FITTING
———————

Calculation engine

cryspy

Minimization engine

lmfit (leastsq)

Fit quality