In [1]:
# Check whether easydiffraction is installed; install it if needed.
# Required for remote environments such as Google Colab.
import importlib.util

if importlib.util.find_spec('easydiffraction') is None:
    %pip install easydiffraction

# Structure Refinement: Taurine, SENJU

Crystal structure refinement of Taurine using time-of-flight single
crystal neutron diffraction data from SENJU at J-PARC.

## Import Library

In [2]:
import easydiffraction as ed

## Step 1: Define Project

In [3]:
# Create minimal project without name and description
project = ed.Project()

## Step 2: Define Structure

In [4]:
# Download CIF file from repository
structure_path = ed.download_data(id=21, destination='data')

Getting data...

Data #21: Taurine (crystal structure)

✅ Data #21 downloaded to 'data/ed-21.cif'

In [5]:
project.structures.add_from_cif_path(structure_path)

In [6]:
project.structures.show_names()

Defined structures 🧩

['taurine']

In [7]:
structure = project.structures['taurine']

In [8]:
structure.show_as_cif()

Structure 🧩 'taurine' as cif

## Step 3: Define Experiment

In [9]:
# Download data file from repository
data_path = ed.download_data(id=22, destination='data')

Getting data...

Data #22: Taurine, SENJU (J-PARC)

✅ Data #22 downloaded to 'data/ed-22.xye'

In [10]:
project.experiments.add_from_data_path(
    name='senju',
    data_path=data_path,
    sample_form='single crystal',
    beam_mode='time-of-flight',
    radiation_probe='neutron',
)

Data loaded successfully

Experiment 🔬 'senju'. Number of data points: 286.

In [11]:
experiment = project.experiments['senju']

In [12]:
experiment.linked_crystal.id = 'taurine'
experiment.linked_crystal.scale = 1.0

In [13]:
experiment.extinction.mosaicity = 1000.0
experiment.extinction.radius = 100.0

## Step 4: Perform Analysis I (ADP iso)

In [14]:
project.display.pattern(expt_name='senju')

In [15]:
experiment.linked_crystal.scale.free = True
experiment.extinction.radius.free = True

In [16]:
project.analysis.fit.show_minimizer_types()

Minimizer types

In [17]:
project.analysis.fit.minimizer_type = 'bumps'

Current minimizer changed to

bumps

In [18]:
# Start refinement. All parameters, which have standard uncertainties
# in the input CIF files, are refined by default.
project.analysis.fit()

Standard fitting

📋 Using experiment 🔬 'senju' for 'single' fitting

🚀 Starting fit process with 'bumps (lm)'...

📈 Goodness-of-fit progress:

🏆 Best goodness-of-fit (reduced χ²) is 23.48 at iteration 5001

✅ Fitting complete.

In [19]:
# Show fit results summary
project.display.fit.results()

Fit results

✅ Success: True

⏱️ Fitting time: 162.67 seconds

📏 Goodness-of-fit (reduced χ²): 23.48

📏 R-factor (Rf): 21.98%

📏 R-factor squared (Rf²): 17.12%

📏 Weighted R-factor (wR): 17.83%

📈 Fitted parameters:

⚠️ Red uncertainty: exceeds the fitted value (consider adding constraints)

In [20]:
structure.show_as_cif()

Structure 🧩 'taurine' as cif

In [21]:
project.experiments.show_names()

Defined experiments 🔬

['senju']

In [22]:
project.display.pattern(expt_name='senju')

## Step 5: Perform Analysis (ADP aniso)

In [23]:
for atom_site in structure.atom_sites:
    atom_site.adp_type = 'Uani'

In [24]:
adp_components = ('adp_11', 'adp_22', 'adp_33', 'adp_12', 'adp_13', 'adp_23')
for atom_site in structure.atom_site_aniso:
    for component in adp_components:
        getattr(atom_site, component).free = True

In [25]:
structure.show_as_cif()

Structure 🧩 'taurine' as cif

In [26]:
project.display.parameters.free()

Free parameters for both structures (🧩 data blocks) and experiments (🔬 data blocks)

In [27]:
project.analysis.fit()

Standard fitting

📋 Using experiment 🔬 'senju' for 'single' fitting

🚀 Starting fit process with 'bumps (lm)'...

📈 Goodness-of-fit progress:

🏆 Best goodness-of-fit (reduced χ²) is 8.73 at iteration 3368

✅ Fitting complete.

⚠️ Parameter 'taurine.atom_site_aniso.S1.adp_11' (-0.02676820) is below its physical lower limit (0.0).

⚠️ Parameter 'taurine.atom_site_aniso.H11.adp_22' (-0.02232498) is below its physical lower limit (0.0).

⚠️ Parameter 'taurine.atom_site_aniso.H22.adp_11' (-0.01401872) is below its physical lower limit (0.0).

In [28]:
project.display.fit.results()

Fit results

✅ Success: True

⏱️ Fitting time: 254.78 seconds

📏 Goodness-of-fit (reduced χ²): 8.73

📏 R-factor (Rf): 11.63%

📏 R-factor squared (Rf²): 7.85%

📏 Weighted R-factor (wR): 6.88%

📈 Fitted parameters:

⚠️ Red fitted value: outside expected physical limits (consider adding constraints)

⚠️ Red uncertainty: exceeds the fitted value (consider adding constraints)

In [29]:
project.display.fit.correlations()

In [30]:
project.display.pattern(expt_name='senju')

In [31]:
structure.show_as_cif()

Structure 🧩 'taurine' as cif