# Structure Refinement: Tb2TiO7, HEiDi

Crystal structure refinement of Tb2TiO7 using single crystal neutron
diffraction data from HEiDi at FRM II.

## Import Library

In [1]:
import easydiffraction as ed

## Step 1: Define Project

In [2]:
# Create minimal project without name and description
project = ed.Project()

## Step 2: Define Structure

In [3]:
# Download CIF file from repository
structure_path = ed.download_data(id=20, destination='data')

Getting data...

Data #20: Tb2Ti2O7 (crystal structure)

✅ Data #20 downloaded to 'data/ed-20.cif'

In [4]:
project.structures.add_from_cif_path(structure_path)

In [5]:
project.structures.show_names()

Defined structures 🧩

['tbti']

In [6]:
structure = project.structures['tbti']

In [7]:
structure.atom_sites['Tb'].b_iso = 0.0
structure.atom_sites['Ti'].b_iso = 0.0
structure.atom_sites['O1'].b_iso = 0.0
structure.atom_sites['O2'].b_iso = 0.0

In [8]:
structure.show_as_cif()

Structure 🧩 'tbti' as cif

## Step 3: Define Experiment

In [9]:
data_path = ed.download_data(id=19, destination='data')

Getting data...

Data #19: Tb2Ti2O7, HEiDi (MLZ)

✅ Data #19 downloaded to 'data/ed-19.xye'

In [10]:
project.experiments.add_from_data_path(
    name='heidi',
    data_path=data_path,
    sample_form='single crystal',
    beam_mode='constant wavelength',
    radiation_probe='neutron',
)

Data loaded successfully

Experiment 🔬 'heidi'. Number of data points: 220

In [11]:
experiment = project.experiments['heidi']  # TODO: <heidi (None)>

In [12]:
experiment.linked_crystal.id = 'tbti'
experiment.linked_crystal.scale = 1.0

In [13]:
experiment.instrument.setup_wavelength = 0.793

In [14]:
experiment.extinction.mosaicity = 29820
experiment.extinction.radius = 30

## Step 4: Perform Analysis

In [15]:
project.plot_meas_vs_calc(expt_name='heidi')

In [16]:
experiment.linked_crystal.scale.free = True
experiment.extinction.radius.free = True

In [17]:
experiment.show_as_cif()

Experiment 🔬 'heidi' as cif

In [18]:
# Start refinement. All parameters, which have standard uncertainties
# in the input CIF files, are refined by default.
project.analysis.fit()

Using experiment 🔬 'heidi' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 12.84 at iteration 73

✅ Fitting complete.

In [19]:
# Show fit results summary
project.analysis.show_fit_results()

Fit results

✅ Success: True

⏱️ Fitting time: 1.82 seconds

📏 Goodness-of-fit (reduced χ²): 12.84

📏 R-factor (Rf): 7.68%

📏 R-factor squared (Rf²): 8.14%

📏 Weighted R-factor (wR): 8.51%

📈 Fitted parameters:

In [20]:
experiment.show_as_cif()

Experiment 🔬 'heidi' as cif

In [21]:
project.experiments.show_names()

Defined experiments 🔬

['heidi']

In [22]:
project.plot_meas_vs_calc(expt_name='heidi')

## Step 5: Show Project Summary

In [23]:
project.summary.show_report()

————————————
PROJECT INFO
————————————

Title

Untitled Project

—————————————————————
CRYSTALLOGRAPHIC DATA
—————————————————————

Phase datablock

🧩 tbti

Space group

F d -3 m

Cell parameters

Atom sites

———————————
EXPERIMENTS
———————————

Experiment datablock

🔬 heidi

Experiment type

single crystal, neutron, constant wavelength

Wavelength

0.79300

———————
FITTING
———————

Calculation engine

  heidi: CalculatorEnum.CRYSPY

Minimization engine

lmfit

Fit quality