In [1]:
# Check whether easydiffraction is installed; install it if needed.
# Required for remote environments such as Google Colab.
import importlib.util

if importlib.util.find_spec('easydiffraction') is None:
    %pip install easydiffraction

# Structure Refinement: Tb2TiO7, HEiDi

Crystal structure refinement of Tb2TiO7 using single crystal neutron
diffraction data from HEiDi at FRM II.

## Import Library

In [2]:
import easydiffraction as ed

## Step 1: Define Project

In [3]:
# Create minimal project without name and description
project = ed.Project(name='tbti_heidi')
project.info.title = 'Tb2Ti2O7 at HEiDi@FRMII'
project.info.description = """This project demonstrates a standard
refinement of the crystal structure of Tb2Ti2O7 using single crystal 
neutron diffraction data from HEiDi at FRM II."""

project.save_as('projects/tbti_heidi')

Saving project 📦 'tbti_heidi' to '../../../projects/tbti_heidi'

├── 📄 project.cif

├── 📁 structures/

├── 📁 experiments/

├── 📁 analysis/

│   └── 📄 analysis.cif

└── 📁 reports/

    └── 📄 tbti_heidi.html

## Step 2: Define Structure

In [4]:
# Download CIF file from repository
structure_path = ed.download_data(id=20, destination='data')

Getting data...

Data #20: Tb2Ti2O7 (crystal structure)

✅ Data #20 downloaded to '../../../data/ed-20.cif'

In [5]:
project.structures.add_from_cif_path(structure_path)

In [6]:
project.structures.show_names()

Defined structures 🧩

['tbti']

In [7]:
structure = project.structures['tbti']

In [8]:
structure.show_as_cif()

Structure 🧩 'tbti' as cif

In [9]:
structure.atom_sites['Tb'].adp_type = 'Uiso'
structure.atom_sites['Ti'].adp_type = 'Uiso'
structure.atom_sites['O1'].adp_type = 'Uiso'
structure.atom_sites['O2'].adp_type = 'Uiso'

In [10]:
print(structure.atom_sites.as_cif)

loop_
_atom_site.label
_atom_site.type_symbol
_atom_site.fract_x
_atom_site.fract_y
_atom_site.fract_z
_atom_site.Wyckoff_symbol
_atom_site.occupancy
_atom_site.U_iso_or_equiv
_atom_site.ADP_type
Tb Tb 0.5 0.5 0.5 d 1. 0.007(20) Uiso
Ti Ti 0. 0. 0. c 1. 0.006(30) Uiso
O1 O 0.328040(90) 0.125 0.125 f 1.000(10) 0.006(20) Uiso
O2 O 0.375 0.375 0.375 b 0.970(20) 0.003(40) Uiso

In [11]:
structure.atom_sites['Tb'].adp_iso = 0.0
structure.atom_sites['Ti'].adp_iso = 0.0
structure.atom_sites['O1'].adp_iso = 0.0
structure.atom_sites['O2'].adp_iso = 0.0

## Step 3: Define Experiment

In [12]:
# Download data file from repository
data_path = ed.download_data(id=19, destination='data')

Getting data...

Data #19: Tb2Ti2O7, HEiDi (MLZ)

✅ Data #19 downloaded to '../../../data/ed-19.xye'

In [13]:
project.experiments.add_from_data_path(
    name='heidi',
    data_path=data_path,
    sample_form='single crystal',
    beam_mode='constant wavelength',
    radiation_probe='neutron',
)

Data loaded successfully

Experiment 🔬 'heidi'. Number of data points: 220.

In [14]:
experiment = project.experiments['heidi']

In [15]:
experiment.linked_crystal.id = 'tbti'
experiment.linked_crystal.scale = 1.0

In [16]:
experiment.instrument.setup_wavelength = 0.793

In [17]:
experiment.extinction.mosaicity = 35000
experiment.extinction.radius = 10

## Step 4: Perform Analysis I (ADP iso)

In [18]:
project.display.pattern(expt_name='heidi')

In [19]:
structure.atom_sites['O1'].fract_x.free = True

structure.atom_sites['Ti'].occupancy.free = True
structure.atom_sites['O1'].occupancy.free = True
structure.atom_sites['O2'].occupancy.free = True

structure.atom_sites['Tb'].adp_iso.free = True
structure.atom_sites['Ti'].adp_iso.free = True
structure.atom_sites['O1'].adp_iso.free = True
structure.atom_sites['O2'].adp_iso.free = True

In [20]:
experiment.linked_crystal.scale.free = True
experiment.extinction.radius.free = True

In [21]:
# Start refinement. All parameters, which have standard uncertainties
# in the input CIF files, are refined by default.
project.analysis.fit()

Standard fitting

📋 Using experiment 🔬 'heidi' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit progress:

🏆 Best goodness-of-fit (reduced χ²) is 12.75 at iteration 80

✅ Fitting complete.

Saving project 📦 'tbti_heidi' to '../../../projects/tbti_heidi'

├── 📄 project.cif

├── 📁 structures/

│   └── 📄 tbti.cif

├── 📁 experiments/

│   └── 📄 heidi.cif

├── 📁 analysis/

│   └── 📄 analysis.cif

└── 📁 reports/

    └── 📄 tbti_heidi.html

In [22]:
# Show fit results summary
project.display.fit.results()

⚙️ Settings used:

📋 Least-squares fit results:

📈 Refined parameters:

In [23]:
structure.show_as_cif()

Structure 🧩 'tbti' as cif

In [24]:
project.experiments.show_names()

Defined experiments 🔬

['heidi']

In [25]:
project.display.pattern(expt_name='heidi')

## Step 5: Perform Analysis (ADP aniso)

In [26]:
structure.atom_sites['Tb'].adp_type = 'Uani'
structure.atom_sites['Ti'].adp_type = 'Uani'
structure.atom_sites['O1'].adp_type = 'Uani'
# structure.atom_sites['O2'].adp_type = 'Uani'

In [27]:
print(structure.atom_site_aniso.as_cif)

loop_
_atom_site_aniso.label
_atom_site_aniso.U_11
_atom_site_aniso.U_22
_atom_site_aniso.U_33
_atom_site_aniso.U_12
_atom_site_aniso.U_13
_atom_site_aniso.U_23
Tb 0.00681683 0.00681683 0.00681683 0. 0. 0.
Ti 0.00539742 0.00539742 0.00539742 0. 0. 0.
O1 0.00572628 0.00572628 0.00572628 0. 0. 0.

In [28]:
structure.atom_site_aniso['Tb'].adp_11.free = True
structure.atom_site_aniso['Tb'].adp_12.free = True
structure.atom_site_aniso['Ti'].adp_11.free = True
structure.atom_site_aniso['Ti'].adp_12.free = True
structure.atom_site_aniso['O1'].adp_11.free = True
structure.atom_site_aniso['O1'].adp_22.free = True
structure.atom_site_aniso['O1'].adp_23.free = True
# structure.atom_site_aniso['O2'].adp_11.free = True

In [29]:
project.analysis.fit()

Standard fitting

📋 Using experiment 🔬 'heidi' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit progress:

🏆 Best goodness-of-fit (reduced χ²) is 2.94 at iteration 78

✅ Fitting complete.

Saving project 📦 'tbti_heidi' to '../../../projects/tbti_heidi'

├── 📄 project.cif

├── 📁 structures/

│   └── 📄 tbti.cif

├── 📁 experiments/

│   └── 📄 heidi.cif

├── 📁 analysis/

│   └── 📄 analysis.cif

└── 📁 reports/

    └── 📄 tbti_heidi.html

In [30]:
project.display.fit.results()

⚙️ Settings used:

📋 Least-squares fit results:

📈 Refined parameters:

In [31]:
project.display.fit.correlations()

In [32]:
project.display.pattern(expt_name='heidi')

In [33]:
structure.show_as_cif()

Structure 🧩 'tbti' as cif

## Step 6: Generate Report

In [34]:
# Enable PDF report generation before the last save (time consuming)
project.report.pdf = True
project.save()

Saving project 📦 'tbti_heidi' to '../../../projects/tbti_heidi'

├── 📄 project.cif

├── 📁 structures/

│   └── 📄 tbti.cif

├── 📁 experiments/

│   └── 📄 heidi.cif

├── 📁 analysis/

│   └── 📄 analysis.cif

└── 📁 reports/

    ├── 📄 tbti_heidi.html

    └── 📄 tbti_heidi.pdf