In [1]:
# Check whether easydiffraction is installed; install it if needed.
# Required for remote environments such as Google Colab.
import importlib.util

if importlib.util.find_spec('easydiffraction') is None:
    %pip install easydiffraction

# Pair Distribution Function: NaCl, XRD

This example demonstrates a pair distribution function (PDF) analysis
of NaCl, based on data collected from an X-ray powder diffraction
experiment.

The dataset is taken from:
https://github.com/diffpy/add2019-diffpy-cmi/tree/master

## Import Library

In [2]:
import easydiffraction as ed

## Create Project

In [3]:
project = ed.Project()

## Set Plotting Engine

In [4]:
# Keep the auto-selected engine. Alternatively, you can uncomment the
# line below to explicitly set the engine to the required one.
# project.plotter.engine = 'plotly'

In [5]:
# Set global plot range for plots
project.plotter.x_min = 2.0
project.plotter.x_max = 30.0

## Add Structure

In [6]:
project.structures.create(name='nacl')

In [7]:
project.structures['nacl'].space_group.name_h_m = 'F m -3 m'
project.structures['nacl'].space_group.it_coordinate_system_code = '1'
project.structures['nacl'].cell.length_a = 5.62
project.structures['nacl'].atom_sites.create(
    label='Na',
    type_symbol='Na',
    fract_x=0,
    fract_y=0,
    fract_z=0,
    wyckoff_letter='a',
    adp_iso=1.0,
)
project.structures['nacl'].atom_sites.create(
    label='Cl',
    type_symbol='Cl',
    fract_x=0.5,
    fract_y=0.5,
    fract_z=0.5,
    wyckoff_letter='b',
    adp_iso=1.0,
)

## Add Experiment

In [8]:
data_path = ed.download_data(id=4, destination='data')

Getting data...

Data #4: NaCl.gr

✅ Data #4 downloaded to 'data/ed-4.gr'

In [9]:
project.experiments.add_from_data_path(
    name='xray_pdf',
    data_path=data_path,
    sample_form='powder',
    beam_mode='constant wavelength',
    radiation_probe='xray',
    scattering_type='total',
)

⚠️ No uncertainty (sy) column provided. Defaulting to 0.03.

Data loaded successfully

Experiment 🔬 'xray_pdf'. Number of data points: 5000.

In [10]:
project.experiments['xray_pdf'].show_supported_peak_profile_types()

Supported types

In [11]:
project.experiments['xray_pdf'].show_current_peak_profile_type()

Current peak profile type

gaussian-damped-sinc

In [12]:
project.experiments['xray_pdf'].peak_profile_type = 'gaussian-damped-sinc'

⚠️ Switching peak profile type discards existing peak parameters.

Peak profile type for experiment 'xray_pdf' changed to

gaussian-damped-sinc

In [13]:
project.experiments['xray_pdf'].peak.damp_q = 0.03
project.experiments['xray_pdf'].peak.broad_q = 0
project.experiments['xray_pdf'].peak.cutoff_q = 21
project.experiments['xray_pdf'].peak.sharp_delta_1 = 0
project.experiments['xray_pdf'].peak.sharp_delta_2 = 5
project.experiments['xray_pdf'].peak.damp_particle_diameter = 0

In [14]:
project.experiments['xray_pdf'].linked_phases.create(id='nacl', scale=0.5)

## Select Fitting Parameters

In [15]:
project.structures['nacl'].cell.length_a.free = True
project.structures['nacl'].atom_sites['Na'].adp_iso.free = True
project.structures['nacl'].atom_sites['Cl'].adp_iso.free = True

In [16]:
project.experiments['xray_pdf'].linked_phases['nacl'].scale.free = True
project.experiments['xray_pdf'].peak.damp_q.free = True
project.experiments['xray_pdf'].peak.sharp_delta_2.free = True

## Run Fitting

In [17]:
project.analysis.fit()
project.analysis.display.fit_results()
project.plotter.plot_param_correlations()

Standard fitting

📋 Using experiment 🔬 'xray_pdf' for 'single' fitting

🚀 Starting fit process with 'bumps (lm)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 1.48 at iteration 59

✅ Fitting complete.

Fit results

✅ Success: True

⏱️ Fitting time: 13.73 seconds

📏 Goodness-of-fit (reduced χ²): 1.48

📏 R-factor (Rf): 11.02%

📏 R-factor squared (Rf²): 11.38%

📏 Weighted R-factor (wR): 11.38%

📈 Fitted parameters:

⚠️ Correlation matrix is unavailable for this fit. Use the lmfit minimizer and ensure covariance estimation succeeds.

## Plot Measured vs Calculated

In [18]:
project.plotter.plot_meas_vs_calc(expt_name='xray_pdf')