# Structure Refinement: HS, HRPT

This example demonstrates a Rietveld refinement of HS crystal
structure using constant wavelength neutron powder diffraction data
from HRPT at PSI.

## Import Library

In [1]:
from easydiffraction import ExperimentFactory
from easydiffraction import Project
from easydiffraction import StructureFactory
from easydiffraction import download_data

## Define Structure

This section shows how to add structures and modify their
parameters.

#### Create Structure

In [2]:
structure = StructureFactory.from_scratch(name='hs')

#### Set Space Group

In [3]:
structure.space_group.name_h_m = 'R -3 m'
structure.space_group.it_coordinate_system_code = 'h'

#### Set Unit Cell

In [4]:
structure.cell.length_a = 6.9
structure.cell.length_c = 14.1

#### Set Atom Sites

In [5]:
structure.atom_sites.create(
    label='Zn',
    type_symbol='Zn',
    fract_x=0,
    fract_y=0,
    fract_z=0.5,
    wyckoff_letter='b',
    b_iso=0.5,
)
structure.atom_sites.create(
    label='Cu',
    type_symbol='Cu',
    fract_x=0.5,
    fract_y=0,
    fract_z=0,
    wyckoff_letter='e',
    b_iso=0.5,
)
structure.atom_sites.create(
    label='O',
    type_symbol='O',
    fract_x=0.21,
    fract_y=-0.21,
    fract_z=0.06,
    wyckoff_letter='h',
    b_iso=0.5,
)
structure.atom_sites.create(
    label='Cl',
    type_symbol='Cl',
    fract_x=0,
    fract_y=0,
    fract_z=0.197,
    wyckoff_letter='c',
    b_iso=0.5,
)
structure.atom_sites.create(
    label='H',
    type_symbol='2H',
    fract_x=0.13,
    fract_y=-0.13,
    fract_z=0.08,
    wyckoff_letter='h',
    b_iso=0.5,
)

## Define Experiment

This section shows how to add experiments, configure their parameters,
and link the structures defined in the previous step.

#### Download Measured Data

In [6]:
data_path = download_data(id=11, destination='data')

Getting data...

Data #11: HS, HRPT (PSI)

✅ Data #11 downloaded to 'data/ed-11.xye'

#### Create Experiment

In [7]:
expt = ExperimentFactory.from_data_path(name='hrpt', data_path=data_path)

Data loaded successfully

Experiment 🔬 'hrpt'. Number of data points: 3220

#### Set Instrument

In [8]:
expt.instrument.setup_wavelength = 1.89
expt.instrument.calib_twotheta_offset = 0.0

#### Set Peak Profile

In [9]:
expt.peak.broad_gauss_u = 0.1
expt.peak.broad_gauss_v = -0.2
expt.peak.broad_gauss_w = 0.2
expt.peak.broad_lorentz_x = 0.0
expt.peak.broad_lorentz_y = 0

#### Set Background

In [10]:
expt.background.create(id='1', x=4.4196, y=500)
expt.background.create(id='2', x=6.6207, y=500)
expt.background.create(id='3', x=10.4918, y=500)
expt.background.create(id='4', x=15.4634, y=500)
expt.background.create(id='5', x=45.6041, y=500)
expt.background.create(id='6', x=74.6844, y=500)
expt.background.create(id='7', x=103.4187, y=500)
expt.background.create(id='8', x=121.6311, y=500)
expt.background.create(id='9', x=159.4116, y=500)

#### Set Linked Phases

In [11]:
expt.linked_phases.create(id='hs', scale=0.5)

## Define Project

The project object is used to manage the structure, experiment, and
analysis.

#### Create Project

In [12]:
project = Project()

#### Set Plotting Engine

In [13]:
# Keep the auto-selected engine. Alternatively, you can uncomment the
# line below to explicitly set the engine to the required one.
# project.plotter.engine = 'plotly'

#### Add Structure

In [14]:
project.structures.add(structure)

#### Add Experiment

In [15]:
project.experiments.add(expt)

## Perform Analysis

This section shows the analysis process, including how to set up
calculation and fitting engines.

#### Set Minimizer

In [16]:
project.analysis.current_minimizer = 'lmfit'

Current minimizer changed to

lmfit

#### Plot Measured vs Calculated

In [17]:
project.plot_meas_vs_calc(expt_name='hrpt', show_residual=True)

In [18]:
project.plot_meas_vs_calc(expt_name='hrpt', x_min=48, x_max=51, show_residual=True)

### Perform Fit 1/5

Set parameters to be refined.

In [19]:
structure.cell.length_a.free = True
structure.cell.length_c.free = True

expt.linked_phases['hs'].scale.free = True
expt.instrument.calib_twotheta_offset.free = True

Show free parameters after selection.

In [20]:
project.analysis.show_free_params()

Free parameters for both structures (🧩 data blocks) and experiments (🔬 data blocks)

#### Run Fitting

In [21]:
project.analysis.fit()

Using experiment 🔬 'hrpt' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 51.57 at iteration 303

✅ Fitting complete.

In [22]:
project.analysis.show_fit_results()

Fit results

✅ Success: True

⏱️ Fitting time: 25.53 seconds

📏 Goodness-of-fit (reduced χ²): 51.57

📏 R-factor (Rf): 19.70%

📏 R-factor squared (Rf²): 30.20%

📏 Weighted R-factor (wR): 30.35%

📈 Fitted parameters:

#### Plot Measured vs Calculated

In [23]:
project.plot_meas_vs_calc(expt_name='hrpt', show_residual=True)

In [24]:
project.plot_meas_vs_calc(expt_name='hrpt', x_min=48, x_max=51, show_residual=True)

### Perform Fit 2/5

Set more parameters to be refined.

In [25]:
expt.peak.broad_gauss_u.free = True
expt.peak.broad_gauss_v.free = True
expt.peak.broad_gauss_w.free = True
expt.peak.broad_lorentz_x.free = True

for point in expt.background:
    point.y.free = True

Show free parameters after selection.

In [26]:
project.analysis.show_free_params()

Free parameters for both structures (🧩 data blocks) and experiments (🔬 data blocks)

#### Run Fitting

In [27]:
project.analysis.fit()

Using experiment 🔬 'hrpt' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 12.41 at iteration 339

✅ Fitting complete.

In [28]:
project.analysis.show_fit_results()

Fit results

✅ Success: True

⏱️ Fitting time: 24.31 seconds

📏 Goodness-of-fit (reduced χ²): 12.41

📏 R-factor (Rf): 9.62%

📏 R-factor squared (Rf²): 12.83%

📏 Weighted R-factor (wR): 12.21%

📈 Fitted parameters:

#### Plot Measured vs Calculated

In [29]:
project.plot_meas_vs_calc(expt_name='hrpt', show_residual=True)

In [30]:
project.plot_meas_vs_calc(expt_name='hrpt', x_min=48, x_max=51, show_residual=True)

### Perform Fit 3/5

Set more parameters to be refined.

In [31]:
structure.atom_sites['O'].fract_x.free = True
structure.atom_sites['O'].fract_z.free = True
structure.atom_sites['Cl'].fract_z.free = True
structure.atom_sites['H'].fract_x.free = True
structure.atom_sites['H'].fract_z.free = True

Show free parameters after selection.

In [32]:
project.analysis.show_free_params()

Free parameters for both structures (🧩 data blocks) and experiments (🔬 data blocks)

#### Run Fitting

In [33]:
project.analysis.fit()

Using experiment 🔬 'hrpt' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.34 at iteration 187

✅ Fitting complete.

In [34]:
project.analysis.show_fit_results()

Fit results

✅ Success: True

⏱️ Fitting time: 13.85 seconds

📏 Goodness-of-fit (reduced χ²): 4.34

📏 R-factor (Rf): 6.01%

📏 R-factor squared (Rf²): 7.74%

📏 Weighted R-factor (wR): 7.51%

📈 Fitted parameters:

#### Plot Measured vs Calculated

In [35]:
project.plot_meas_vs_calc(expt_name='hrpt', show_residual=True)

In [36]:
project.plot_meas_vs_calc(expt_name='hrpt', x_min=48, x_max=51, show_residual=True)

### Perform Fit 4/5

Set more parameters to be refined.

In [37]:
structure.atom_sites['Zn'].b_iso.free = True
structure.atom_sites['Cu'].b_iso.free = True
structure.atom_sites['O'].b_iso.free = True
structure.atom_sites['Cl'].b_iso.free = True
structure.atom_sites['H'].b_iso.free = True

Show free parameters after selection.

In [38]:
project.analysis.show_free_params()

Free parameters for both structures (🧩 data blocks) and experiments (🔬 data blocks)

#### Run Fitting

In [39]:
project.analysis.fit()

Using experiment 🔬 'hrpt' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 2.11 at iteration 118

✅ Fitting complete.

In [40]:
project.analysis.show_fit_results()

Fit results

✅ Success: True

⏱️ Fitting time: 10.56 seconds

📏 Goodness-of-fit (reduced χ²): 2.11

📏 R-factor (Rf): 4.17%

📏 R-factor squared (Rf²): 5.05%

📏 Weighted R-factor (wR): 4.73%

📈 Fitted parameters:

#### Plot Measured vs Calculated

In [41]:
project.plot_meas_vs_calc(expt_name='hrpt', show_residual=True)

In [42]:
project.plot_meas_vs_calc(expt_name='hrpt', x_min=48, x_max=51, show_residual=True)

## Summary

This final section shows how to review the results of the analysis.

#### Show Project Summary

In [43]:
project.summary.show_report()

————————————
PROJECT INFO
————————————

Title

Untitled Project

—————————————————————
CRYSTALLOGRAPHIC DATA
—————————————————————

Phase datablock

🧩 hs

Space group

R -3 m

Cell parameters

Atom sites

———————————
EXPERIMENTS
———————————

Experiment datablock

🔬 hrpt

Experiment type

powder, neutron, constant wavelength

Wavelength

1.89000

2θ offset

0.11368

Profile type

PeakProfileTypeEnum.PSEUDO_VOIGT

Peak broadening (Gaussian)

Peak broadening (Lorentzian)

———————
FITTING
———————

Calculation engine

  hrpt: CalculatorEnum.CRYSPY

Minimization engine

lmfit

Fit quality