In [1]:
# Check whether easydiffraction is installed; install it if needed.
# Required for remote environments such as Google Colab.
import importlib.util

if importlib.util.find_spec('easydiffraction') is None:
    %pip install easydiffraction

# Load Project and Fit: LBCO, HRPT

This is the most minimal example of using EasyDiffraction. It shows
how to load a previously saved project from a directory and run
refinement — all in just a few lines of code.

For this example, constant-wavelength neutron powder diffraction data
for La0.5Ba0.5CoO3 from HRPT at PSI is used.

It does not contain any advanced features or options, and includes no
comments or explanations — these can be found in the other tutorials.

## Import Modules

In [2]:
from easydiffraction import Project
from easydiffraction import download_data

## Download Saved Project

In [3]:
project_dir = download_data(id=36, destination='projects')

Getting data...

Data #36: La0.5Ba0.5CoO3, HRPT (PSI), 300 K - Updated #30

✅ Data #36 downloaded and extracted to '/home/runner/work/diffraction-lib/diffraction-lib/tmp/tutorials/projects/ed-36/lbco_hrpt'

## Load Project

In [4]:
project = Project.load(project_dir)

## Perform Analysis

In [5]:
project.analysis.fit()

Standard fitting

📋 Using experiment 🔬 'hrpt' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit progress:

🏆 Best goodness-of-fit (reduced χ²) is 1.29 at iteration 11

✅ Fitting complete.

Saving project 📦 'lbco_hrpt' to

/home/runner/work/diffraction-lib/diffraction-lib/tmp/tutorials/projects/ed-36/lbco_hrpt

├── 📄 project.cif

├── 📁 structures/

│   └── 📄 lbco.cif

├── 📁 experiments/

│   └── 📄 hrpt.cif

├── 📁 analysis/

│   └── 📄 analysis.cif

└── 📄 summary.cif

## Show Results

In [6]:
project.display.fit.results()

Fit results

✅ Success: True

⏱️ Fitting time: 1.58 seconds

📏 Goodness-of-fit (reduced χ²): 1.29

📏 R-factor (Rf): 5.62%

📏 R-factor squared (Rf²): 5.26%

📏 Weighted R-factor (wR): 4.42%

📈 Fitted parameters:

In [7]:
project.display.fit.correlations()

In [8]:
project.display.pattern(expt_name='hrpt')