In [1]:
# Check whether easydiffraction is installed; install it if needed.
# Required for remote environments such as Google Colab.
import importlib.util

if importlib.util.find_spec('easydiffraction') is None:
    %pip install easydiffraction

# Load Project and Fit: LBCO, HRPT

This is the most minimal example of using EasyDiffraction. It shows
how to load a previously saved project from a directory and run
refinement — all in just a few lines of code.

For this example, constant-wavelength neutron powder diffraction data
for La0.5Ba0.5CoO3 from HRPT at PSI is used.

It does not contain any advanced features or options, and includes no
comments or explanations — these can be found in the other tutorials.

## Import Modules

In [2]:
from easydiffraction import Project
from easydiffraction import download_data
from easydiffraction import extract_project_from_zip

## Download Project Archive

In [3]:
zip_path = download_data(id=30, destination='data')

Getting data...

Data #30: La0.5Ba0.5CoO3, HRPT (PSI), 300 K - Updated #28

✅ Data #30 downloaded to 'data/ed-30.zip'

## Extract Project

In [4]:
project_dir = extract_project_from_zip(zip_path, destination='data')

## Load Project

In [5]:
project = Project.load(project_dir)

## Perform Analysis

In [6]:
project.analysis.fit()

Standard fitting

📋 Using experiment 🔬 'hrpt' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 1.25 at iteration 328

✅ Fitting complete.

Saving project 📦 'lbco_hrpt' to

/home/runner/work/diffraction-lib/diffraction-lib/docs/docs/tutorials/data/lbco_project

├── 📄 project.cif

├── 📁 structures/

│   └── 📄 lbco.cif

├── 📁 experiments/

│   └── 📄 hrpt.cif

├── 📁 analysis/

│   └── 📄 analysis.cif

└── 📄 summary.cif

## Show Results

In [7]:
project.analysis.display.fit_results()

Fit results

✅ Success: True

⏱️ Fitting time: 18.35 seconds

📏 Goodness-of-fit (reduced χ²): 1.25

📏 R-factor (Rf): 5.48%

📏 R-factor squared (Rf²): 4.94%

📏 Weighted R-factor (wR): 3.97%

📈 Fitted parameters:

#### Show parameter correlations

In [8]:
project.plotter.plot_param_correlations()

## Plot Meas vs Calc

In [9]:
project.plotter.plot_meas_vs_calc(expt_name='hrpt', show_residual=True)