In [1]:
# Check whether easydiffraction is installed; install it if needed.
# Required for remote environments such as Google Colab.
import importlib.util

if importlib.util.find_spec('easydiffraction') is None:
    %pip install easydiffraction

# Structure Refinement: Co2SiO4, D20

This example demonstrates a Rietveld refinement of Co2SiO4 crystal
structure using constant wavelength neutron powder diffraction data
from D20 at ILL.

## Import Library

In [2]:
from easydiffraction import ExperimentFactory
from easydiffraction import Project
from easydiffraction import StructureFactory
from easydiffraction import download_data

## Define Structure

This section shows how to add structures and modify their
parameters.

#### Create Structure

In [3]:
structure = StructureFactory.from_scratch(name='cosio')

#### Set Space Group

In [4]:
structure.space_group.name_h_m = 'P n m a'
structure.space_group.it_coordinate_system_code = 'abc'

#### Set Unit Cell

In [5]:
structure.cell.length_a = 10.3
structure.cell.length_b = 6.0
structure.cell.length_c = 4.8

#### Set Atom Sites

In [6]:
structure.atom_sites.create(
    label='Co1',
    type_symbol='Co',
    fract_x=0,
    fract_y=0,
    fract_z=0,
    wyckoff_letter='a',
    adp_iso=0.5,
)
structure.atom_sites.create(
    label='Co2',
    type_symbol='Co',
    fract_x=0.279,
    fract_y=0.25,
    fract_z=0.985,
    wyckoff_letter='c',
    adp_iso=0.5,
)
structure.atom_sites.create(
    label='Si',
    type_symbol='Si',
    fract_x=0.094,
    fract_y=0.25,
    fract_z=0.429,
    wyckoff_letter='c',
    adp_iso=0.5,
)
structure.atom_sites.create(
    label='O1',
    type_symbol='O',
    fract_x=0.091,
    fract_y=0.25,
    fract_z=0.771,
    wyckoff_letter='c',
    adp_iso=0.5,
)
structure.atom_sites.create(
    label='O2',
    type_symbol='O',
    fract_x=0.448,
    fract_y=0.25,
    fract_z=0.217,
    wyckoff_letter='c',
    adp_iso=0.5,
)
structure.atom_sites.create(
    label='O3',
    type_symbol='O',
    fract_x=0.164,
    fract_y=0.032,
    fract_z=0.28,
    wyckoff_letter='d',
    adp_iso=0.5,
)

## Define Experiment

This section shows how to add experiments, configure their parameters,
and link the structures defined in the previous step.

#### Download Measured Data

In [7]:
data_path = download_data(id=12, destination='data')

Getting data...

Data #12: Co2SiO4, D20 (ILL)

✅ Data #12 downloaded to 'data/ed-12.xye'

#### Create Experiment

In [8]:
expt = ExperimentFactory.from_data_path(name='d20', data_path=data_path)

#### Set Instrument

In [9]:
expt.instrument.setup_wavelength = 1.87
expt.instrument.calib_twotheta_offset = 0.1

#### Set Peak Profile

In [10]:
expt.show_peak_profile_types()
expt.peak_profile_type = 'pseudo-voigt + empirical asymmetry'
expt.peak.broad_gauss_u = 0.3
expt.peak.broad_gauss_v = -0.5
expt.peak.broad_gauss_w = 0.4

Peak profile types

⚠️ Switching peak profile type discards existing peak parameters.

Peak profile type for experiment 'd20' changed to

pseudo-voigt + empirical asymmetry

#### Set Background

In [11]:
expt.show_background_types()
expt.background.create(id='1', x=8, y=500)
expt.background.create(id='2', x=9, y=500)
expt.background.create(id='3', x=10, y=500)
expt.background.create(id='4', x=11, y=500)
expt.background.create(id='5', x=12, y=500)
expt.background.create(id='6', x=15, y=500)
expt.background.create(id='7', x=25, y=500)
expt.background.create(id='8', x=30, y=500)
expt.background.create(id='9', x=50, y=500)
expt.background.create(id='10', x=70, y=500)
expt.background.create(id='11', x=90, y=500)
expt.background.create(id='12', x=110, y=500)
expt.background.create(id='13', x=130, y=500)
expt.background.create(id='14', x=150, y=500)

Background types

#### Set Linked Phases

In [12]:
expt.linked_phases.create(id='cosio', scale=1.0)

## Define Project

The project object is used to manage the structure, experiment, and
analysis.

#### Create Project

In [13]:
project = Project()

#### Add Structure

In [14]:
project.structures.add(structure)

#### Add Experiment

In [15]:
project.experiments.add(expt)

## Perform Analysis

This section shows the analysis process, including how to set up
calculation and fitting engines.

#### Plot Measured vs Calculated

In [16]:
project.display.plotter.plot_meas_vs_calc(expt_name='d20', show_residual=True)

In [17]:
project.display.plotter.plot_meas_vs_calc(expt_name='d20', x_min=41, x_max=54, show_residual=True)

#### Set Free Parameters

In [18]:
structure.cell.length_a.free = True
structure.cell.length_b.free = True
structure.cell.length_c.free = True

structure.atom_sites['Co2'].fract_x.free = True
structure.atom_sites['Co2'].fract_z.free = True
structure.atom_sites['Si'].fract_x.free = True
structure.atom_sites['Si'].fract_z.free = True
structure.atom_sites['O1'].fract_x.free = True
structure.atom_sites['O1'].fract_z.free = True
structure.atom_sites['O2'].fract_x.free = True
structure.atom_sites['O2'].fract_z.free = True
structure.atom_sites['O3'].fract_x.free = True
structure.atom_sites['O3'].fract_y.free = True
structure.atom_sites['O3'].fract_z.free = True

structure.atom_sites['Co1'].adp_iso.free = True
structure.atom_sites['Co2'].adp_iso.free = True
structure.atom_sites['Si'].adp_iso.free = True
structure.atom_sites['O1'].adp_iso.free = True
structure.atom_sites['O2'].adp_iso.free = True
structure.atom_sites['O3'].adp_iso.free = True

In [19]:
expt.linked_phases['cosio'].scale.free = True

expt.instrument.calib_twotheta_offset.free = True

expt.peak.broad_gauss_u.free = True
expt.peak.broad_gauss_v.free = True
expt.peak.broad_gauss_w.free = True
expt.peak.broad_lorentz_y.free = True

expt.peak.asym_empir_2.free = True

for point in expt.background:
    point.y.free = True

#### Set Constraints

Set aliases for parameters.

In [20]:
project.analysis.aliases.create(
    label='biso_Co1',
    param=project.structures['cosio'].atom_sites['Co1'].adp_iso,
)
project.analysis.aliases.create(
    label='biso_Co2',
    param=project.structures['cosio'].atom_sites['Co2'].adp_iso,
)

Set constraints.

In [21]:
project.analysis.constraints.create(expression='biso_Co2 = biso_Co1')

#### Run Fitting

In [22]:
project.analysis.fit()

Standard fitting

📋 Using experiment 🔬 'd20' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.50 at iteration 521

✅ Fitting complete.

In [23]:
project.analysis.display.fit_results()

Fit results

✅ Success: True

⏱️ Fitting time: 28.27 seconds

📏 Goodness-of-fit (reduced χ²): 4.50

📏 R-factor (Rf): 3.02%

📏 R-factor squared (Rf²): 4.50%

📏 Weighted R-factor (wR): 4.82%

📈 Fitted parameters:

In [24]:
project.display.plotter.plot_param_correlations()

#### Plot Measured vs Calculated

In [25]:
project.display.plotter.plot_meas_vs_calc(expt_name='d20', show_residual=True)

In [26]:
project.display.plotter.plot_meas_vs_calc(expt_name='d20', x_min=42, x_max=52, show_residual=True)

## Perform Analysis (ADP aniso)

In [27]:
for label in ('O1', 'O2', 'O3'):
    atom_site = structure.atom_sites[label]
    atom_site.occupancy.free = True

In [28]:
for label in ('O1', 'O2', 'O3'):
    atom_site = structure.atom_sites[label]
    atom_site.adp_type = 'Uani'
    atom_site_aniso = structure.atom_site_aniso[label]
    for component in ('adp_11', 'adp_22', 'adp_33', 'adp_12', 'adp_13', 'adp_23'):
        getattr(atom_site_aniso, component).free = True

In [29]:
structure.show_as_cif()

Structure 🧩 'cosio' as cif

In [30]:
project.analysis.display.free_params()

Free parameters for both structures (🧩 data blocks) and experiments (🔬 data blocks)

In [31]:
project.analysis.fit()

Standard fitting

📋 Using experiment 🔬 'd20' for 'single' fitting

🚀 Starting fit process with 'lmfit (leastsq)'...

📈 Goodness-of-fit (reduced χ²) change:

🏆 Best goodness-of-fit (reduced χ²) is 4.44 at iteration 278

✅ Fitting complete.

In [32]:
project.analysis.display.fit_results()

Fit results

✅ Success: True

⏱️ Fitting time: 18.13 seconds

📏 Goodness-of-fit (reduced χ²): 4.44

📏 R-factor (Rf): 2.99%

📏 R-factor squared (Rf²): 4.34%

📏 Weighted R-factor (wR): 4.57%

📈 Fitted parameters:

In [33]:
project.display.plotter.plot_param_correlations()

⚠️ Correlation matrix is unavailable for this fit. Use the lmfit minimizer and ensure covariance estimation succeeds.

In [34]:
project.display.plotter.plot_meas_vs_calc(expt_name='d20', show_residual=True)

In [35]:
project.display.plotter.plot_meas_vs_calc(expt_name='d20', x_min=42, x_max=52, show_residual=True)

In [36]:
structure.show_as_cif()

Structure 🧩 'cosio' as cif

## Summary

This final section shows how to review the results of the analysis.

#### Show Project Summary

In [37]:
project.summary.show_report()

————————————
PROJECT INFO
————————————

Title

Untitled Project

—————————————————————
CRYSTALLOGRAPHIC DATA
—————————————————————

Phase datablock

🧩 cosio

Space group

P n m a

Atom sites

———————————
EXPERIMENTS
———————————

Experiment datablock

🔬 d20

Experiment type

powder, neutron, constant wavelength bragg

Calculation engine

cryspy

Wavelength

1.87000

2θ offset

0.27619

Profile type

pseudo-voigt + empirical asymmetry

Peak broadening (Gaussian)

Peak broadening (Lorentzian)

Asymmetry (Empirical)

———————
FITTING
———————

Minimization engine

lmfit (leastsq)

Fit quality